import "server-only";
import { getSetting } from "@/lib/settings/store";

/**
 * Email design system. Table-based, inline-styled HTML (Gmail / Outlook /
 * Apple Mail safe) that mirrors the site: navy header with the logo, white
 * card, yellow primary button, Manrope with system fallback, 14–16px text,
 * footer with company, contact and legal links. Every template composes
 * these blocks; `text` renders the same content as plain text.
 */
export const BRAND = { navy: "#122A58", blue: "#1D428A", yellow: "#F1C400", red: "#D62828", green: "#1E7B3C", ink: "#1a1a1a", ink2: "#4d4d4d", muted: "#7a7a7a", line: "#e6e8ee", surface: "#f5f6f9" };
const FONT = "Manrope, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif";

export interface EmailCtx { baseUrl: string; siteName: string; phone: string; email: string; address: string; legalName: string; unsubscribeUrl?: string | null; year: number }

export async function emailCtx(extra: Partial<EmailCtx> = {}): Promise<EmailCtx> {
  const { data } = await getSetting("general").catch(() => ({ data: {} as Record<string, string> }));
  const baseUrl = String(data.baseUrl || process.env.AUTH_URL || "https://www.euronics.gr").replace(/\/$/, "");
  return { baseUrl, siteName: String(data.siteName || "Euronics"), phone: String(data.phone || "210 483 5143"), email: String(data.email || "info@euronics.gr"), address: String(data.address || "Δαμάσκου 2 Σταμάτη 12, 135 71 Αχαρνές"), legalName: String(data.legalName || "MEGA ELECTRICS ΑΕΒΕ"), year: new Date().getFullYear(), ...extra };
}

export const esc = (s: string | number | null | undefined) => String(s ?? "").replace(/[&<>"]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" })[c]!);
export const money = (n: number) => `${n.toLocaleString("el-GR", { minimumFractionDigits: 2, maximumFractionDigits: 2 })} €`;
const abs = (ctx: EmailCtx, u: string | null | undefined) => (!u ? "" : /^https?:/.test(u) ? u : `${ctx.baseUrl}${u}`);
/** Email clients do not render WebP/AVIF/SVG: JPEG/PNG/GIF pass through, anything else goes through the on-demand JPEG route. Media-library assets should pass their `emailUrl` directly. */
export const emailImg = (ctx: EmailCtx, u: string | null | undefined) => { if (!u) return ""; const url = abs(ctx, u); return /\.(jpe?g|png|gif)(\?|$)/i.test(url) ? url : `${ctx.baseUrl}/api/img/email?src=${encodeURIComponent(u.startsWith("/") ? u : url)}`; };

/* ---------- blocks: each returns { html, text } ---------- */
export type Block = { html: string; text: string };
export const h1 = (t: string): Block => ({ html: `<h1 style="margin:0 0 12px;font-family:${FONT};font-size:26px;line-height:1.2;font-weight:800;color:${BRAND.ink}">${esc(t)}</h1>`, text: `${t}\n${"=".repeat(Math.min(60, t.length))}` });
export const h2 = (t: string): Block => ({ html: `<h2 style="margin:20px 0 8px;font-family:${FONT};font-size:17px;line-height:1.3;font-weight:800;color:${BRAND.ink}">${esc(t)}</h2>`, text: `\n${t}` });
export const p = (t: string, opts: { muted?: boolean; small?: boolean } = {}): Block => ({ html: `<p style="margin:0 0 12px;font-family:${FONT};font-size:${opts.small ? 14 : 16}px;line-height:1.55;color:${opts.muted ? BRAND.muted : BRAND.ink2}">${t}</p>`, text: t.replace(/<[^>]+>/g, "") });
export const button = (label: string, href: string, variant: "primary" | "secondary" = "primary"): Block => ({ html: `<table role="presentation" cellspacing="0" cellpadding="0" border="0" style="margin:8px 0 16px"><tr><td style="border-radius:999px;background:${variant === "primary" ? BRAND.yellow : BRAND.navy}"><a href="${esc(href)}" style="display:inline-block;padding:14px 26px;font-family:${FONT};font-size:16px;font-weight:800;color:${variant === "primary" ? BRAND.navy : "#fff"};text-decoration:none;border-radius:999px">${esc(label)}</a></td></tr></table>`, text: `${label}: ${href}` });
export const note = (t: string, tone: "info" | "success" | "warning" | "danger" = "info"): Block => { const c = { info: [BRAND.surface, BRAND.navy], success: ["#e8f3ec", BRAND.green], warning: ["#fdf6d8", "#7a5c00"], danger: ["#fbe9e9", BRAND.red] }[tone]; return { html: `<table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="margin:0 0 14px"><tr><td style="background:${c[0]};border-left:4px solid ${c[1]};border-radius:10px;padding:12px 14px;font-family:${FONT};font-size:14px;line-height:1.5;color:${BRAND.ink}">${t}</td></tr></table>`, text: `[${t.replace(/<[^>]+>/g, "")}]` }; };
export const otp = (code: string): Block => ({ html: `<table role="presentation" cellspacing="0" cellpadding="0" style="margin:6px 0 14px"><tr><td style="background:${BRAND.navy};border-radius:16px;padding:16px 28px;font-family:${FONT};font-size:36px;letter-spacing:10px;font-weight:800;color:${BRAND.yellow}">${esc(code)}</td></tr></table>`, text: `\nΚΩΔΙΚΟΣ: ${code}\n` });
export const divider = (): Block => ({ html: `<hr style="border:0;border-top:1px solid ${BRAND.line};margin:18px 0">`, text: "\n" + "-".repeat(40) });
export const kv = (rows: [string, string][]): Block => ({ html: `<table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="margin:0 0 14px;font-family:${FONT};font-size:14px">${rows.map(([k, v]) => `<tr><td style="padding:6px 0;color:${BRAND.muted};width:42%;vertical-align:top">${esc(k)}</td><td style="padding:6px 0;color:${BRAND.ink};font-weight:700">${v}</td></tr>`).join("")}</table>`, text: rows.map(([k, v]) => `${k}: ${v.replace(/<[^>]+>/g, "")}`).join("\n") });
export const steps = (items: { label: string; done?: boolean; current?: boolean }[]): Block => ({ html: `<table role="presentation" cellspacing="0" cellpadding="0" style="margin:0 0 16px"><tr>${items.map((s, i) => `<td style="padding:0 10px 0 0;font-family:${FONT};font-size:14px;font-weight:700;color:${s.current ? BRAND.navy : s.done ? BRAND.green : BRAND.muted};white-space:nowrap">${s.done ? "✓ " : `${i + 1}. `}${esc(s.label)}</td>`).join("")}</tr></table>`, text: items.map((s, i) => `${s.done ? "✓" : i + 1}. ${s.label}${s.current ? " ←" : ""}`).join("  ") });
export const lines = (ctx: EmailCtx, items: { title: string; brand?: string; image?: string | null; qty: number; unitPrice: number; addons?: { title: string; price: number }[] }[]): Block => ({
  html: `<table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="margin:0 0 8px;border-top:1px solid ${BRAND.line}">${items.map((l) => `<tr><td style="padding:12px 0;border-bottom:1px solid ${BRAND.line};width:72px;vertical-align:top">${l.image ? `<img src="${esc(emailImg(ctx, l.image))}" width="64" height="64" alt="" style="display:block;width:64px;height:64px;object-fit:contain;border-radius:10px;background:${BRAND.surface}">` : `<div style="width:64px;height:64px;border-radius:10px;background:${BRAND.surface}"></div>`}</td><td style="padding:12px 8px;border-bottom:1px solid ${BRAND.line};vertical-align:top;font-family:${FONT}"><div style="font-size:14px;font-weight:700;color:${BRAND.muted}">${esc(l.brand ?? "")}</div><div style="font-size:15px;font-weight:700;color:${BRAND.ink};line-height:1.35">${esc(l.title)}</div>${(l.addons ?? []).map((a) => `<div style="font-size:14px;color:${BRAND.ink2}">+ ${esc(a.title)} · ${money(a.price)}</div>`).join("")}<div style="font-size:14px;color:${BRAND.muted}">Ποσότητα ${l.qty}</div></td><td style="padding:12px 0;border-bottom:1px solid ${BRAND.line};text-align:right;vertical-align:top;font-family:${FONT};font-size:15px;font-weight:800;color:${BRAND.ink};white-space:nowrap">${money(l.unitPrice * l.qty)}</td></tr>`).join("")}</table>`,
  text: items.map((l) => `- ${l.qty}× ${l.brand ?? ""} ${l.title} — ${money(l.unitPrice * l.qty)}${(l.addons ?? []).map((a) => `\n    + ${a.title} ${money(a.price)}`).join("")}`).join("\n"),
});
export const totals = (rows: [string, number | string][], grand: [string, number]): Block => ({ html: `<table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="margin:0 0 16px;font-family:${FONT};font-size:14px">${rows.map(([k, v]) => `<tr><td style="padding:4px 0;color:${BRAND.ink2}">${esc(k)}</td><td style="padding:4px 0;text-align:right;color:${BRAND.ink}">${typeof v === "number" ? money(v) : esc(v)}</td></tr>`).join("")}<tr><td style="padding:10px 0 0;font-size:17px;font-weight:800;color:${BRAND.ink};border-top:2px solid ${BRAND.navy}">${esc(grand[0])}</td><td style="padding:10px 0 0;text-align:right;font-size:20px;font-weight:800;color:${BRAND.navy};border-top:2px solid ${BRAND.navy}">${money(grand[1])}</td></tr></table>`, text: rows.map(([k, v]) => `${k}: ${typeof v === "number" ? money(v) : v}`).join("\n") + `\n${grand[0]}: ${money(grand[1])}` });
export const storeCard = (ctx: EmailCtx, s: { name: string; address: string; city: string; zip: string; phone?: string | null; hours?: string; lat?: number; lng?: number }): Block => ({ html: `<table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="margin:0 0 14px"><tr><td style="background:${BRAND.surface};border-radius:14px;padding:14px 16px;font-family:${FONT};font-size:14px;line-height:1.5;color:${BRAND.ink}"><div style="font-weight:800;font-size:15px">${esc(s.name)}</div><div>${esc(s.address)}, ${esc(s.zip)} ${esc(s.city)}</div>${s.hours ? `<div style="color:${BRAND.ink2}">${esc(s.hours)}</div>` : ""}${s.phone ? `<div><a href="tel:${esc(s.phone)}" style="color:${BRAND.blue};font-weight:700;text-decoration:none">${esc(s.phone)}</a></div>` : ""}${s.lat && s.lng ? `<div style="margin-top:6px"><a href="https://maps.google.com/?q=${s.lat},${s.lng}" style="color:${BRAND.blue};font-weight:700">Οδηγίες στο Google Maps →</a></div>` : ""}</td></tr></table>`, text: `${s.name}\n${s.address}, ${s.zip} ${s.city}${s.phone ? `\n${s.phone}` : ""}${s.hours ? `\n${s.hours}` : ""}` });
export const products = (ctx: EmailCtx, items: { title: string; brand: string; image?: string | null; price: number; wasPrice?: number | null; href: string }[]): Block => ({ html: `<table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="margin:0 0 16px"><tr>${items.slice(0, 3).map((it) => `<td width="33%" style="padding:0 6px;vertical-align:top"><a href="${esc(abs(ctx, it.href))}" style="text-decoration:none;color:${BRAND.ink};font-family:${FONT}"><div style="background:${BRAND.surface};border-radius:12px;padding:10px;text-align:center">${it.image ? `<img src="${esc(emailImg(ctx, it.image))}" width="120" alt="" style="display:block;margin:0 auto;width:120px;height:120px;object-fit:contain">` : ""}</div><div style="font-size:14px;font-weight:700;color:${BRAND.muted};margin-top:6px">${esc(it.brand)}</div><div style="font-size:14px;font-weight:700;line-height:1.3">${esc(it.title)}</div><div style="font-size:15px;font-weight:800;color:${BRAND.navy};margin-top:4px">${money(it.price)}${it.wasPrice ? ` <span style="font-size:14px;color:${BRAND.muted};text-decoration:line-through;font-weight:400">${money(it.wasPrice)}</span>` : ""}</div></a></td>`).join("")}</tr></table>`, text: items.map((it) => `- ${it.brand} ${it.title} — ${money(it.price)} ${abs(ctx, it.href)}`).join("\n") });
export const aris = (ctx: EmailCtx, quote: string): Block => ({ html: `<table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="margin:6px 0 16px"><tr><td width="56" style="vertical-align:top"><img src="${emailImg(ctx, "/img/advisor/mascot-head.webp")}" width="48" height="48" alt="Άρης" style="display:block;width:48px;height:48px;border-radius:50%;border:3px solid ${BRAND.yellow}"></td><td style="padding-left:10px;vertical-align:top;font-family:${FONT};font-size:14px;line-height:1.5;color:${BRAND.ink2}"><div style="font-size:14px;font-weight:800;color:${BRAND.blue};text-transform:uppercase;letter-spacing:.04em">Ο Άρης λέει</div>${esc(quote)}</td></tr></table>`, text: `Ο Άρης: ${quote}` });

/** Wrap blocks in the brand shell. */
export function renderEmail(ctx: EmailCtx, opts: { subject: string; preheader?: string; blocks: Block[]; footerNote?: string; marketing?: boolean }): { subject: string; html: string; text: string } {
  const body = opts.blocks.map((b) => b.html).join("\n");
  const text = [opts.preheader ?? "", ...opts.blocks.map((b) => b.text), "", `${ctx.legalName} · ${ctx.address} · Τηλ. ${ctx.phone}`, opts.marketing && ctx.unsubscribeUrl ? `Διαγραφή: ${ctx.unsubscribeUrl}` : ""].filter(Boolean).join("\n");
  const html = `<!doctype html><html lang="el"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="light"><title>${esc(opts.subject)}</title><link href="https://fonts.googleapis.com/css2?family=Manrope:wght@400;700;800&display=swap" rel="stylesheet"><style>@media (max-width:640px){.container{width:100%!important}.card{padding:22px 18px!important}.stack td{display:block;width:100%!important;padding:0 0 12px!important}}</style></head>
<body style="margin:0;padding:0;background:${BRAND.surface};-webkit-font-smoothing:antialiased">
<div style="display:none;max-height:0;overflow:hidden;opacity:0">${esc(opts.preheader ?? "")}&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;</div>
<table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="background:${BRAND.surface}"><tr><td align="center" style="padding:24px 12px">
<table role="presentation" class="container" width="600" cellspacing="0" cellpadding="0" style="width:600px;max-width:100%">
<tr><td style="background:${BRAND.navy};border-radius:20px 20px 0 0;padding:20px 28px"><table role="presentation" width="100%" cellspacing="0" cellpadding="0"><tr><td><a href="${ctx.baseUrl}" style="text-decoration:none"><img src="${ctx.baseUrl}/design/euronics-logo-white.png" width="140" alt="${esc(ctx.siteName)}" style="display:block;width:140px;height:auto"></a></td><td align="right" style="font-family:${FONT};font-size:14px;color:#9fb0d3">350 καταστήματα σε όλη την Ελλάδα</td></tr></table></td></tr>
<tr><td class="card" style="background:#ffffff;padding:32px 36px;border-left:1px solid ${BRAND.line};border-right:1px solid ${BRAND.line}">${body}</td></tr>
<tr><td style="background:#ffffff;border-radius:0 0 20px 20px;border:1px solid ${BRAND.line};border-top:0;padding:18px 36px 24px;font-family:${FONT};font-size:14px;line-height:1.55;color:${BRAND.muted}">${opts.footerNote ? `<p style="margin:0 0 10px">${opts.footerNote}</p>` : ""}<p style="margin:0 0 6px"><b style="color:${BRAND.ink2}">${esc(ctx.legalName)}</b> · ${esc(ctx.address)}<br>Τηλ. <a href="tel:${esc(ctx.phone)}" style="color:${BRAND.blue};text-decoration:none">${esc(ctx.phone)}</a> · <a href="mailto:${esc(ctx.email)}" style="color:${BRAND.blue};text-decoration:none">${esc(ctx.email)}</a></p><p style="margin:0"><a href="${ctx.baseUrl}/aporrito" style="color:${BRAND.muted}">Πολιτική Απορρήτου</a> · <a href="${ctx.baseUrl}/oroi-xrisis" style="color:${BRAND.muted}">Όροι χρήσης</a>${opts.marketing && ctx.unsubscribeUrl ? ` · <a href="${esc(ctx.unsubscribeUrl)}" style="color:${BRAND.muted}">Διαγραφή από το newsletter</a>` : ""}</p></td></tr>
<tr><td style="padding:14px 0 0;text-align:center;font-family:${FONT};font-size:14px;color:${BRAND.muted}">© ${ctx.year} ${esc(ctx.siteName)} · euronics.gr</td></tr>
</table></td></tr></table></body></html>`;
  return { subject: opts.subject, html, text };
}
