import "server-only";
import { renderEmail, emailCtx, h1, h2, p, button, note, otp, divider, kv, steps, lines, totals, storeCard, products, aris, esc, money, type EmailCtx, type Block } from "./layout";

/**
 * Every customer-facing email, grouped by the job that triggers it. Each
 * template renders subject + HTML + text from typed data and ships a sample
 * so the back office can preview it. Add a template here → it appears in
 * /admin/emails automatically.
 */
export type EmailGroup = "account" | "newsletter" | "orders" | "service" | "wishlist" | "gdpr" | "cart" | "loyalty";
export const EMAIL_GROUPS: { key: EmailGroup; label: string; blurb: string }[] = [
  { key: "account", label: "Λογαριασμός & ασφάλεια", blurb: "Εγγραφή, επιβεβαίωση email, κωδικοί, νέες συσκευές." },
  { key: "orders", label: "Παραγγελίες", blurb: "Από την επιβεβαίωση μέχρι την παράδοση ή την παραλαβή, επιστροφές." },
  { key: "service", label: "Service & εγγυήσεις", blurb: "Αιτήματα, ραντεβού τεχνικού, υπενθυμίσεις, εγγυήσεις που λήγουν." },
  { key: "cart", label: "Καλάθι & Ερμής", blurb: "Εγκαταλελειμμένο καλάθι, αποστολή καλαθιού με email." },
  { key: "wishlist", label: "Αγαπημένα", blurb: "Πτώση τιμής, διαθεσιμότητα." },
  { key: "newsletter", label: "Newsletter", blurb: "Double opt-in, καλωσόρισμα, διαγραφή." },
  { key: "loyalty", label: "Πόντοι & γενέθλια", blurb: "Πόντοι που κερδήθηκαν, δώρο γενεθλίων." },
  { key: "gdpr", label: "GDPR", blurb: "Παράδοση δεδομένων, επιβεβαίωση διαγραφής." },
];

export interface EmailTemplate<D = unknown> { key: string; group: EmailGroup; name: string; description: string; trigger: string; marketing?: boolean; sample: () => D; render: (d: D, ctx: EmailCtx) => { subject: string; html: string; text: string } }

const SAMPLE_LINES = [
  { title: '43NANO82T6B NanoCell 43" 4K Smart TV', brand: "LG", image: "/img/products/p-lg-43nano82-0.jpg", qty: 1, unitPrice: 349, addons: [{ title: "Επέκταση εγγύησης +2 έτη", price: 39 }] },
  { title: "Flip 7 Φορητό Ηχείο Bluetooth", brand: "JBL", image: "/img/products/speaker.jpg", qty: 1, unitPrice: 129 },
];
const STORE = { name: "Euronics Αθήνα — ΜΠΡΙΛΑΚΗ ΑΦΟΙ Ε.Ε", address: "Μεσογείων 64", city: "Αθήνα", zip: "11527", phone: "2107709247", hours: "Δευ–Παρ 09:00–21:00, Σάβ 09:00–18:00", lat: 37.9865, lng: 23.769 };
const PRODUCTS = [
  { title: 'OLED evo C4 55" 4K', brand: "LG", image: "/img/cutouts/oled-tv.webp", price: 1299, wasPrice: 1599, href: "/proion/lg-oled55c4" },
  { title: "Airfryer XXL HD9285 7,2 L", brand: "Philips", image: "/img/cutouts/airfryer.webp", price: 179, wasPrice: 219, href: "/proion/philips-airfryer" },
  { title: "Πλυντήριο 9kg 1400 στροφών", brand: "AEG", image: "/img/cutouts/cooker.webp", price: 549, wasPrice: null, href: "/proion/aeg-lr7f49gs" },
];
const name = (d: { firstName?: string }) => d.firstName || "φίλε μας";
const t = <D,>(x: EmailTemplate<D>) => x as unknown as EmailTemplate;
const security = (ctx: EmailCtx, extra?: string) => p(`Αν δεν το ζήτησες εσύ, αγνόησε αυτό το μήνυμα${extra ? ` — ${extra}` : ""}. Η ${esc(ctx.siteName)} δεν θα σου ζητήσει ποτέ κωδικούς τηλεφωνικά.`, { muted: true, small: true });

export const EMAIL_TEMPLATES: EmailTemplate[] = [
  /* ---------- account ---------- */
  t<{ firstName: string; verifyUrl: string }>({ key: "account-welcome", group: "account", name: "Καλωσόρισμα", description: "Μετά τη δημιουργία λογαριασμού, με σύνδεσμο επιβεβαίωσης email.", trigger: "Εγγραφή πελάτη (checkout ή social login)", sample: () => ({ firstName: "Μαρία", verifyUrl: "https://www.euronics.gr/api/account/verify?token=demo" }), render: (d, ctx) => renderEmail(ctx, { subject: `Καλώς ήρθες στη ${ctx.siteName}, ${d.firstName}!`, preheader: "Ένα κλικ για να επιβεβαιώσεις το email σου.", blocks: [h1(`Καλώς ήρθες, ${d.firstName}!`), p("Ο λογαριασμός σου είναι έτοιμος. Επιβεβαίωσε το email σου για να ενεργοποιηθούν οι ειδοποιήσεις παραγγελιών, οι εγγυήσεις των συσκευών σου και τα αγαπημένα σε όλες τις συσκευές."), button("Επιβεβαίωση email", d.verifyUrl), aris(ctx, "Αν ψάχνεις κάτι, ρώτα με. Ξέρω και ποιο κατάστημα είναι πιο κοντά σου."), divider(), kv([["Παραγγελίες", `<a href="${ctx.baseUrl}/logariasmos/paraggelies" style="color:#1D428A">Παρακολούθηση & ιστορικό</a>`], ["Εγγυήσεις", `<a href="${ctx.baseUrl}/logariasmos/eggyiseis" style="color:#1D428A">Οι συσκευές μου</a>`], ["Καταστήματα", `<a href="${ctx.baseUrl}/katastimata" style="color:#1D428A">350 σε όλη την Ελλάδα</a>`]]), security(ctx)] }) }),
  t<{ firstName: string; code: string; minutes: number; ip: string | null; device: string | null }>({ key: "password-otp", group: "account", name: "Κωδικός επαναφοράς (OTP)", description: "6ψήφιος κωδικός μιας χρήσης για την επαναφορά κωδικού.", trigger: "«Ξέχασα τον κωδικό» ή αποστολή από τη διαχείριση", sample: () => ({ firstName: "Μαρία", code: "719232", minutes: 10, ip: "94.66.12.8", device: "iOS 18 · Safari 18" }), render: (d, ctx) => renderEmail(ctx, { subject: `${d.code} — ο κωδικός επαναφοράς σου`, preheader: `Ισχύει για ${d.minutes} λεπτά.`, blocks: [h1("Επαναφορά κωδικού"), p(`Γεια σου ${esc(name(d))}, αυτός είναι ο κωδικός μιας χρήσης για τον λογαριασμό σου:`), otp(d.code), p(`Ισχύει για <b>${d.minutes} λεπτά</b>. Γράψε τον στη σελίδα επαναφοράς και όρισε νέο κωδικό.`), note(`Αίτημα από ${esc(d.ip ?? "άγνωστη IP")}${d.device ? ` · ${esc(d.device)}` : ""}, ${new Date().toLocaleString("el-GR")}.`, "info"), security(ctx, "ο κωδικός σου δεν αλλάζει")] }) }),
  t<{ firstName: string; when: string; ip: string | null; device: string | null }>({ key: "password-changed", group: "account", name: "Ο κωδικός άλλαξε", description: "Ειδοποίηση ασφαλείας μετά από αλλαγή κωδικού.", trigger: "Επιτυχής επαναφορά ή αλλαγή κωδικού", sample: () => ({ firstName: "Μαρία", when: new Date().toLocaleString("el-GR"), ip: "94.66.12.8", device: "macOS 15 · Chrome 152" }), render: (d, ctx) => renderEmail(ctx, { subject: "Ο κωδικός σου άλλαξε", preheader: "Αν δεν ήσουν εσύ, κάλεσέ μας αμέσως.", blocks: [h1("Ο κωδικός σου άλλαξε"), p(`Γεια σου ${esc(name(d))}, ο κωδικός του λογαριασμού σου άλλαξε στις <b>${esc(d.when)}</b>${d.ip ? ` από ${esc(d.ip)}` : ""}${d.device ? ` (${esc(d.device)})` : ""}.`), note(`Δεν ήσουν εσύ; Κάλεσέ μας <b>αμέσως</b> στο <a href="tel:${esc(ctx.phone)}" style="color:#D62828;font-weight:800">${esc(ctx.phone)}</a> για να κλειδώσουμε τον λογαριασμό.`, "danger"), button("Σύνδεση στον λογαριασμό", `${ctx.baseUrl}/syndesi`, "secondary")] }) }),
  t<{ firstName: string; when: string; ip: string | null; device: string | null; city: string | null }>({ key: "login-new-device", group: "account", name: "Σύνδεση από νέα συσκευή", description: "Ειδοποίηση όταν γίνεται σύνδεση από άγνωστη συσκευή/τοποθεσία.", trigger: "Επιτυχής σύνδεση με νέο user agent ή IP", sample: () => ({ firstName: "Μαρία", when: new Date().toLocaleString("el-GR"), ip: "185.4.22.9", device: "Android 15 · Chrome 152", city: "Θεσσαλονίκη" }), render: (d, ctx) => renderEmail(ctx, { subject: "Νέα σύνδεση στον λογαριασμό σου", preheader: `${d.device ?? "Νέα συσκευή"}${d.city ? ` · ${d.city}` : ""}`, blocks: [h1("Νέα σύνδεση"), p(`Γεια σου ${esc(name(d))}, έγινε σύνδεση στον λογαριασμό σου από συσκευή που δεν είχαμε ξαναδεί.`), kv([["Πότε", esc(d.when)], ["Συσκευή", esc(d.device ?? "—")], ["Περιοχή", esc(d.city ?? "—")], ["IP", esc(d.ip ?? "—")]]), p("Αν ήσουν εσύ, δεν χρειάζεται να κάνεις κάτι."), note(`Αν δεν ήσουν εσύ, άλλαξε τον κωδικό σου τώρα και κάλεσέ μας στο <b>${esc(ctx.phone)}</b>.`, "warning"), button("Αλλαγή κωδικού", `${ctx.baseUrl}/ksexasa-kodiko`)] }) }),
  /* ---------- newsletter ---------- */
  t<{ firstName: string | null; confirmUrl: string }>({ key: "newsletter-confirm", group: "newsletter", name: "Επιβεβαίωση εγγραφής (double opt-in)", description: "Ο σύνδεσμος που επιβεβαιώνει την εγγραφή στο newsletter.", trigger: "Εγγραφή από footer, checkout, popup ή διαχείριση", sample: () => ({ firstName: "Μαρία", confirmUrl: "https://www.euronics.gr/api/newsletter/confirm?token=demo" }), render: (d, ctx) => renderEmail(ctx, { subject: "Επιβεβαίωσε την εγγραφή σου στο newsletter", preheader: "Ένα κλικ και είσαι μέσα.", blocks: [h1("Σχεδόν έτοιμο!"), p(`Γεια σου${d.firstName ? ` ${esc(d.firstName)}` : ""}, πάτησε για να επιβεβαιώσεις ότι θέλεις να λαμβάνεις το newsletter της ${esc(ctx.siteName)}: πραγματικές προσφορές, ένα email την εβδομάδα.`), button("Επιβεβαίωση εγγραφής", d.confirmUrl), p("Αν δεν ζήτησες εσύ την εγγραφή, αγνόησε αυτό το μήνυμα — δεν θα λάβεις τίποτα άλλο.", { muted: true, small: true })] }) }),
  t<{ firstName: string | null }>({ key: "newsletter-welcome", group: "newsletter", name: "Καλωσόρισμα στο newsletter", description: "Μετά την επιβεβαίωση, με τις τρέχουσες προσφορές.", trigger: "Επιβεβαίωση double opt-in", marketing: true, sample: () => ({ firstName: "Μαρία" }), render: (d, ctx) => renderEmail(ctx, { subject: "Είσαι μέσα! Οι πρώτες προσφορές σου", preheader: "Ένα email την εβδομάδα, μόνο ό,τι αξίζει.", marketing: true, blocks: [h1(`Καλώς ήρθες${d.firstName ? `, ${esc(d.firstName)}` : ""}!`), p("Η εγγραφή σου επιβεβαιώθηκε. Να τι ξεχωρίζει αυτή την εβδομάδα:"), products(ctx, PRODUCTS), button("Όλες οι προσφορές", `${ctx.baseUrl}/prosfores`), aris(ctx, "Πες μου τι ψάχνεις και θα σου βρω το σωστό, στη σωστή τιμή.")] }) }),
  t<{ email: string }>({ key: "newsletter-unsubscribed", group: "newsletter", name: "Επιβεβαίωση διαγραφής", description: "Επιβεβαίωση ότι η διαγραφή από το newsletter ολοκληρώθηκε.", trigger: "Σύνδεσμος διαγραφής ή διαγραφή από διαχείριση", sample: () => ({ email: "maria@example.gr" }), render: (d, ctx) => renderEmail(ctx, { subject: "Διαγράφηκες από το newsletter", preheader: "Δεν θα ξαναλάβεις εμπορική επικοινωνία.", blocks: [h1("Διαγράφηκες"), p(`Το ${esc(d.email)} δεν θα λαμβάνει πλέον newsletter από τη ${esc(ctx.siteName)}. Τα emails για τις παραγγελίες και τις εγγυήσεις σου συνεχίζουν κανονικά.`), button("Ξανά εγγραφή", `${ctx.baseUrl}/newsletter`, "secondary")] }) }),
  /* ---------- orders ---------- */
  t<{ firstName: string; number: string; lines: typeof SAMPLE_LINES; subtotal: number; shippingFee: number; total: number; payment: string; fulfilment: "courier" | "click-collect" | "appointment"; address?: string; store?: typeof STORE; eta: string }>({ key: "order-confirmation", group: "orders", name: "Επιβεβαίωση παραγγελίας", description: "Απόδειξη παραγγελίας με προϊόντα, ποσά, τρόπο παράδοσης και πληρωμής.", trigger: "Ολοκλήρωση checkout", sample: () => ({ firstName: "Μαρία", number: "EUR-20260904-0417", lines: SAMPLE_LINES, subtotal: 517, shippingFee: 0, total: 517, payment: "Κάρτα •••• 4821 · 12 άτοκες δόσεις", fulfilment: "courier", address: "Μαρία Παπαδοπούλου, Μεσογείων 64, 3ος, 11527 Αθήνα · 6944123456", eta: "Τετάρτη 10 Σεπτεμβρίου" }), render: (d, ctx) => renderEmail(ctx, { subject: `Λάβαμε την παραγγελία σου ${d.number}`, preheader: `${d.lines.length} προϊόντα · ${money(d.total)} · ${d.eta}`, blocks: [h1(`Ευχαριστούμε, ${esc(d.firstName)}!`), p(`Η παραγγελία <b>${esc(d.number)}</b> καταχωρήθηκε. Θα σε ενημερώσουμε σε κάθε βήμα.`), steps([{ label: "Καταχωρήθηκε", done: true }, { label: "Ετοιμάζεται", current: true }, { label: d.fulfilment === "click-collect" ? "Έτοιμη για παραλαβή" : "Σε αποστολή" }, { label: d.fulfilment === "click-collect" ? "Παραλήφθηκε" : "Παραδόθηκε" }]), lines(ctx, d.lines), totals([["Υποσύνολο", d.subtotal], ["Μεταφορικά", d.shippingFee === 0 ? "Δωρεάν" : d.shippingFee]], ["Σύνολο", d.total]), h2(d.fulfilment === "click-collect" ? "Παραλαβή από κατάστημα" : d.fulfilment === "appointment" ? "Παράδοση με ραντεβού" : "Παράδοση με courier"), d.store ? storeCard(ctx, d.store) : kv([["Διεύθυνση", esc(d.address ?? "")], ["Εκτίμηση", esc(d.eta)]]), kv([["Πληρωμή", esc(d.payment)]]), button("Παρακολούθηση παραγγελίας", `${ctx.baseUrl}/logariasmos/paraggelies/${d.number}`), aris(ctx, "Θέλεις εγκατάσταση ή ανακύκλωση της παλιάς συσκευής; Μπορείς να τα προσθέσεις μέχρι την αποστολή.")] }) }),
  t<{ firstName: string; number: string; courier: string; code: string; url: string; eta: string }>({ key: "order-shipped", group: "orders", name: "Η παραγγελία στάλθηκε", description: "Courier, αριθμός αποστολής, σύνδεσμος παρακολούθησης, εκτίμηση παράδοσης.", trigger: "Κατάσταση → shipped (ERP / courier webhook)", sample: () => ({ firstName: "Μαρία", number: "EUR-20260904-0417", courier: "ACS Courier", code: "1234567890", url: "https://www.acscourier.net/el/track/1234567890", eta: "αύριο 10:00–15:00" }), render: (d, ctx) => renderEmail(ctx, { subject: `Η παραγγελία ${d.number} είναι καθ' οδόν`, preheader: `${d.courier} · παράδοση ${d.eta}`, blocks: [h1("Ξεκίνησε!"), p(`Γεια σου ${esc(d.firstName)}, η παραγγελία <b>${esc(d.number)}</b> παραδόθηκε στην ${esc(d.courier)}.`), steps([{ label: "Καταχωρήθηκε", done: true }, { label: "Ετοιμάστηκε", done: true }, { label: "Σε αποστολή", current: true }, { label: "Παραδόθηκε" }]), kv([["Courier", esc(d.courier)], ["Αριθμός αποστολής", `<span style="font-family:monospace">${esc(d.code)}</span>`], ["Εκτιμώμενη παράδοση", esc(d.eta)]]), button("Παρακολούθηση αποστολής", d.url), p("Θα χρειαστεί κάποιος να παραλάβει. Αν δεν είσαι εκεί, ο courier θα ξαναπροσπαθήσει την επόμενη εργάσιμη.", { muted: true, small: true })] }) }),
  t<{ firstName: string; number: string; store: typeof STORE; until: string; code: string }>({ key: "order-ready-for-pickup", group: "orders", name: "Έτοιμη για παραλαβή", description: "Το κατάστημα, το ωράριο, μέχρι πότε και ο κωδικός παραλαβής.", trigger: "Κατάσταση → ready-for-pickup (Click & Collect)", sample: () => ({ firstName: "Μαρία", number: "EUR-20260904-0417", store: STORE, until: "Σάββατο 13 Σεπτεμβρίου", code: "EU-4417" }), render: (d, ctx) => renderEmail(ctx, { subject: `Η παραγγελία ${d.number} σε περιμένει στο κατάστημα`, preheader: `${d.store.name} · έως ${d.until}`, blocks: [h1("Έτοιμη για παραλαβή!"), p(`Γεια σου ${esc(d.firstName)}, η παραγγελία <b>${esc(d.number)}</b> είναι στο κατάστημα. Κρατάμε τα προϊόντα μέχρι <b>${esc(d.until)}</b>.`), storeCard(ctx, d.store), h2("Στο ταμείο δείξε"), otp(d.code), p("Τον κωδικό παραλαβής και μια ταυτότητα. Αν παραλάβει άλλο άτομο, χρειάζεται τον κωδικό και το όνομά σου.", { small: true }), button("Οδηγίες προς το κατάστημα", `https://maps.google.com/?q=${d.store.lat},${d.store.lng}`)] }) }),
  t<{ firstName: string; number: string; reviewUrl: string; items: typeof PRODUCTS }>({ key: "order-delivered", group: "orders", name: "Παραδόθηκε + αξιολόγηση", description: "Επιβεβαίωση παράδοσης, εγγύηση καταχωρήθηκε, πρόσκληση για αξιολόγηση.", trigger: "Κατάσταση → delivered (+3 ημέρες για την αξιολόγηση)", sample: () => ({ firstName: "Μαρία", number: "EUR-20260904-0417", reviewUrl: "https://www.euronics.gr/logariasmos/paraggelies/EUR-20260904-0417#review", items: PRODUCTS.slice(0, 2) }), render: (d, ctx) => renderEmail(ctx, { subject: "Παραδόθηκε! Πώς σου φαίνεται;", preheader: "Η εγγύηση καταχωρήθηκε αυτόματα στον λογαριασμό σου.", blocks: [h1("Καλή χρήση!"), p(`Η παραγγελία <b>${esc(d.number)}</b> παραδόθηκε. Οι συσκευές μπήκαν αυτόματα στις <a href="${ctx.baseUrl}/logariasmos/eggyiseis" style="color:#1D428A">εγγυήσεις</a> του λογαριασμού σου — ό,τι χρειαστείς, το service είναι ένα κλικ.`), products(ctx, d.items), p("Δύο λεπτά για μια αξιολόγηση βοηθούν τον επόμενο πελάτη — και σου δίνουν 50 πόντους."), button("Γράψε αξιολόγηση", d.reviewUrl), aris(ctx, "Αν κάτι δεν δουλεύει όπως περίμενες, πες μου. Κλείνουμε τεχνικό της γειτονιάς σου.")] }) }),
  t<{ firstName: string; number: string; reason: string; refund: number | null; method: string }>({ key: "order-cancelled", group: "orders", name: "Ακύρωση παραγγελίας", description: "Ακύρωση με λόγο και πληροφορίες επιστροφής χρημάτων.", trigger: "Κατάσταση → cancelled", sample: () => ({ firstName: "Μαρία", number: "EUR-20260904-0417", reason: "Μετά από αίτημά σου", refund: 517, method: "Κάρτα •••• 4821 (3–5 εργάσιμες)" }), render: (d, ctx) => renderEmail(ctx, { subject: `Η παραγγελία ${d.number} ακυρώθηκε`, preheader: d.refund ? `Επιστροφή ${money(d.refund)}` : "", blocks: [h1("Ακύρωση παραγγελίας"), p(`Γεια σου ${esc(d.firstName)}, η παραγγελία <b>${esc(d.number)}</b> ακυρώθηκε (${esc(d.reason)}).`), d.refund ? note(`Επιστροφή <b>${money(d.refund)}</b> στο ${esc(d.method)}.`, "success") : p("Δεν έγινε χρέωση."), button("Συνέχισε τις αγορές", `${ctx.baseUrl}/prosfores`, "secondary")] }) }),
  t<{ firstName: string; number: string; rma: string; items: string[]; refund: number; method: string }>({ key: "order-return", group: "orders", name: "Επιστροφή προϊόντος", description: "Παραλάβαμε την επιστροφή, ποσό και τρόπος επιστροφής χρημάτων.", trigger: "Επιστροφή παραλήφθηκε / εγκρίθηκε", sample: () => ({ firstName: "Μαρία", number: "EUR-20260904-0417", rma: "RMA-2211", items: ["JBL Flip 7 Φορητό Ηχείο Bluetooth"], refund: 129, method: "Κάρτα •••• 4821" }), render: (d, ctx) => renderEmail(ctx, { subject: `Παραλάβαμε την επιστροφή ${d.rma}`, preheader: `Επιστροφή ${money(d.refund)} στην κάρτα σου.`, blocks: [h1("Επιστροφή παραλήφθηκε"), p(`Γεια σου ${esc(d.firstName)}, παραλάβαμε και ελέγξαμε την επιστροφή <b>${esc(d.rma)}</b> της παραγγελίας ${esc(d.number)}.`), kv([["Προϊόντα", d.items.map(esc).join("<br>")], ["Ποσό", money(d.refund)], ["Επιστροφή σε", esc(d.method)], ["Χρόνος", "3–5 εργάσιμες ημέρες"]]), p("Ευχαριστούμε για την εμπιστοσύνη — ελπίζουμε να τα ξαναπούμε σύντομα.", { muted: true, small: true })] }) }),
  /* ---------- service ---------- */
  t<{ firstName: string; number: string; device: string; description: string; mode: string }>({ key: "service-received", group: "service", name: "Λάβαμε το αίτημα service", description: "Επιβεβαίωση αιτήματος με αριθμό και επόμενα βήματα.", trigger: "Νέο αίτημα από τον λογαριασμό ή τη διαχείριση", sample: () => ({ firstName: "Μαρία", number: "SRV-10001", device: "Samsung Πλυντήριο 9kg WW90T4040", description: "Δεν στύβει, θόρυβος στο στύψιμο", mode: "Επίσκεψη τεχνικού" }), render: (d, ctx) => renderEmail(ctx, { subject: `Λάβαμε το αίτημά σου ${d.number}`, preheader: "Θα σε καλέσουμε για ραντεβού μέσα σε 1 εργάσιμη.", blocks: [h1("Το αίτημά σου καταχωρήθηκε"), p(`Γεια σου ${esc(d.firstName)}, καταγράψαμε το αίτημα <b>${esc(d.number)}</b>.`), kv([["Συσκευή", esc(d.device)], ["Περιγραφή", esc(d.description)], ["Τρόπος", esc(d.mode)]]), steps([{ label: "Καταχωρήθηκε", done: true }, { label: "Ραντεβού", current: true }, { label: "Επισκευή" }, { label: "Ολοκληρώθηκε" }]), p("Ο τεχνικός του κοντινότερου καταστήματος θα σε καλέσει για ραντεβού μέσα σε μία εργάσιμη ημέρα. Αν η συσκευή είναι σε εγγύηση, δεν υπάρχει χρέωση."), button("Το αίτημά μου", `${ctx.baseUrl}/logariasmos/rantevou`, "secondary")] }) }),
  t<{ firstName: string; number: string; date: string; slot: string; technician: string; store: typeof STORE; address: string }>({ key: "appointment-confirmed", group: "service", name: "Ραντεβού επιβεβαιώθηκε", description: "Ημέρα, ζώνη ώρας, τεχνικός, κατάστημα, οδηγίες προετοιμασίας.", trigger: "Αίτημα → scheduled", sample: () => ({ firstName: "Μαρία", number: "SRV-10001", date: "Πέμπτη 18 Σεπτεμβρίου", slot: "Πρωί 9:00–13:00", technician: "Κ. Δημητρίου", store: STORE, address: "Μεσογείων 64, 3ος, 11527 Αθήνα" }), render: (d, ctx) => renderEmail(ctx, { subject: `Ραντεβού ${d.date}, ${d.slot} — ${d.number}`, preheader: `Τεχνικός ${d.technician}`, blocks: [h1("Το ραντεβού σου"), p(`Γεια σου ${esc(d.firstName)}, κλείσαμε ραντεβού για το αίτημα <b>${esc(d.number)}</b>.`), kv([["Πότε", `<b>${esc(d.date)}</b>, ${esc(d.slot)}`], ["Πού", esc(d.address)], ["Τεχνικός", esc(d.technician)], ["Από το κατάστημα", esc(d.store.name)]]), note("Πριν την επίσκεψη: άδειασε τον χώρο γύρω από τη συσκευή και έχε πρόχειρη την απόδειξη αγοράς αν είναι εκτός λογαριασμού.", "info"), button("Αλλαγή ραντεβού", `${ctx.baseUrl}/logariasmos/rantevou`, "secondary"), p(`Θα λάβεις υπενθύμιση την προηγούμενη ημέρα. Για αλλαγές κάλεσε το κατάστημα στο ${esc(d.store.phone ?? "")}.`, { muted: true, small: true })] }) }),
  t<{ firstName: string; number: string; date: string; slot: string; technician: string }>({ key: "appointment-reminder", group: "service", name: "Υπενθύμιση ραντεβού", description: "Την προηγούμενη ημέρα του ραντεβού.", trigger: "Cron: 24 ώρες πριν το ραντεβού", sample: () => ({ firstName: "Μαρία", number: "SRV-10001", date: "αύριο, Πέμπτη 18 Σεπτεμβρίου", slot: "9:00–13:00", technician: "Κ. Δημητρίου" }), render: (d, ctx) => renderEmail(ctx, { subject: `Υπενθύμιση: ραντεβού ${d.date}`, preheader: `${d.slot} · ${d.technician}`, blocks: [h1("Τα λέμε αύριο"), p(`Γεια σου ${esc(d.firstName)}, ο τεχνικός <b>${esc(d.technician)}</b> έρχεται ${esc(d.date)}, ${esc(d.slot)} (αίτημα ${esc(d.number)}).`), note("Θα σε καλέσει 30 λεπτά πριν φτάσει.", "info"), button("Λεπτομέρειες ραντεβού", `${ctx.baseUrl}/logariasmos/rantevou`, "secondary")] }) }),
  t<{ firstName: string; number: string; device: string; work: string; cost: number | null }>({ key: "service-done", group: "service", name: "Το service ολοκληρώθηκε", description: "Τι έγινε, κόστος (αν υπήρξε), εγγύηση επισκευής.", trigger: "Αίτημα → done", sample: () => ({ firstName: "Μαρία", number: "SRV-10001", device: "Samsung Πλυντήριο 9kg WW90T4040", work: "Αντικατάσταση ρουλεμάν κάδου, έλεγχος αντλίας", cost: null }), render: (d, ctx) => renderEmail(ctx, { subject: `Ολοκληρώθηκε το service ${d.number}`, preheader: d.cost ? `Κόστος ${money(d.cost)}` : "Χωρίς χρέωση (εγγύηση)", blocks: [h1("Έτοιμο!"), p(`Γεια σου ${esc(d.firstName)}, η επισκευή της συσκευής <b>${esc(d.device)}</b> ολοκληρώθηκε.`), kv([["Εργασίες", esc(d.work)], ["Κόστος", d.cost ? money(d.cost) : "Χωρίς χρέωση — εντός εγγύησης"], ["Εγγύηση επισκευής", "6 μήνες"]]), p("Αν το πρόβλημα επανεμφανιστεί, απάντησε σε αυτό το email ή άνοιξε νέο αίτημα από τον λογαριασμό σου."), button("Αξιολόγησε το service", `${ctx.baseUrl}/logariasmos/rantevou`, "secondary")] }) }),
  t<{ firstName: string; device: string; until: string; extendUrl: string; price: number }>({ key: "warranty-expiring", group: "service", name: "Η εγγύηση λήγει", description: "60 ημέρες πριν τη λήξη, με πρόταση επέκτασης.", trigger: "Cron: 60 ημέρες πριν το warrantyUntil", marketing: true, sample: () => ({ firstName: "Μαρία", device: 'LG OLED evo C4 55"', until: "20 Νοεμβρίου 2026", extendUrl: "https://www.euronics.gr/logariasmos/eggyiseis", price: 79 }), render: (d, ctx) => renderEmail(ctx, { subject: `Η εγγύηση της ${d.device} λήγει ${d.until}`, preheader: `Επέκταση 2 έτη από ${money(d.price)}.`, marketing: true, blocks: [h1("Η εγγύηση λήγει σύντομα"), p(`Γεια σου ${esc(d.firstName)}, η εγγύηση της συσκευής <b>${esc(d.device)}</b> λήγει στις <b>${esc(d.until)}</b>.`), note(`Επέκταση εγγύησης +2 έτη από <b>${money(d.price)}</b>: επισκευή ή αντικατάσταση χωρίς χρέωση, τεχνικός στο σπίτι.`, "success"), button("Επέκταση εγγύησης", d.extendUrl), aris(ctx, "Τα περισσότερα προβλήματα στις τηλεοράσεις εμφανίζονται τον 3ο-4ο χρόνο. Η επέκταση συμφέρει.")] }) }),
  /* ---------- cart ---------- */
  t<{ firstName: string; lines: typeof SAMPLE_LINES; total: number; cartUrl: string }>({ key: "cart-abandoned", group: "cart", name: "Εγκαταλελειμμένο καλάθι", description: "Ο Ερμής θυμίζει το καλάθι με τα προϊόντα και βοήθεια.", trigger: "2 ώρες χωρίς ολοκλήρωση, με συναίνεση marketing", marketing: true, sample: () => ({ firstName: "Μαρία", lines: SAMPLE_LINES, total: 517, cartUrl: "https://www.euronics.gr/kalathi" }), render: (d, ctx) => renderEmail(ctx, { subject: "Το καλάθι σου σε περιμένει", preheader: `${d.lines.length} προϊόντα · ${money(d.total)}`, marketing: true, blocks: [h1(`Ξέχασες κάτι, ${esc(d.firstName)};`), aris(ctx, "Κράτησα το καλάθι σου. Αν έχεις απορία για κάποιο προϊόν, ρώτα με πριν αποφασίσεις."), lines(ctx, d.lines), totals([], ["Σύνολο", d.total]), button("Επιστροφή στο καλάθι", d.cartUrl), p("Δωρεάν μεταφορικά εντός περιφέρειας · δόσεις με ή χωρίς κάρτα · παραλαβή σε 2 ώρες από 350 καταστήματα.", { muted: true, small: true })] }) }),
  t<{ firstName: string; lines: typeof SAMPLE_LINES; total: number; cartUrl: string; reason: string }>({ key: "cart-emailed", group: "cart", name: "Το καλάθι σου με email", description: "Όταν ο πελάτης φεύγει και ζητά να του στείλουμε το καλάθι (exit intent).", trigger: "Exit intent → «Στείλε μου το καλάθι»", sample: () => ({ firstName: "Μαρία", lines: SAMPLE_LINES, total: 517, cartUrl: "https://www.euronics.gr/kalathi?restore=demo", reason: "Θέλω να το δω με τον σύζυγό μου" }), render: (d, ctx) => renderEmail(ctx, { subject: "Το καλάθι σου, όπως το ζήτησες", preheader: `${d.lines.length} προϊόντα · ${money(d.total)}`, blocks: [h1("Το καλάθι σου"), p(`Όπως ζήτησες, ${esc(d.firstName)}: το καλάθι σου, με έναν σύνδεσμο που το ανοίγει σε όποια συσκευή θέλεις.`), lines(ctx, d.lines), totals([], ["Σύνολο", d.total]), button("Άνοιγμα καλαθιού", d.cartUrl), p("Οι τιμές ισχύουν για 48 ώρες. Οι προσφορές ενδέχεται να αλλάξουν μετά.", { muted: true, small: true })] }) }),
  /* ---------- wishlist ---------- */
  t<{ firstName: string; product: (typeof PRODUCTS)[number]; was: number; now: number }>({ key: "wishlist-price-drop", group: "wishlist", name: "Πτώση τιμής", description: "Ένα αγαπημένο προϊόν έπεσε σε τιμή από τότε που αποθηκεύτηκε.", trigger: "Συγχρονισμός τιμών με χαμηλότερη τιμή από το priceAtAdd", marketing: true, sample: () => ({ firstName: "Μαρία", product: PRODUCTS[0], was: 1599, now: 1299 }), render: (d, ctx) => renderEmail(ctx, { subject: `Έπεσε η τιμή: ${d.product.brand} ${d.product.title} −${money(d.was - d.now)}`, preheader: `Τώρα ${money(d.now)} (ήταν ${money(d.was)})`, marketing: true, blocks: [h1("Έπεσε η τιμή!"), p(`Γεια σου ${esc(d.firstName)}, το προϊόν που αποθήκευσες στα αγαπημένα κοστίζει τώρα <b style="color:#D62828">${money(d.now)}</b> αντί ${money(d.was)}.`), products(ctx, [{ ...d.product, price: d.now, wasPrice: d.was }]), button("Δες το προϊόν", `${ctx.baseUrl}${d.product.href}`), p("Οι τιμές αλλάζουν συχνά — η ειδοποίηση στέλνεται μία φορά ανά πτώση.", { muted: true, small: true })] }) }),
  t<{ firstName: string; product: (typeof PRODUCTS)[number]; store: string | null }>({ key: "wishlist-back-in-stock", group: "wishlist", name: "Ξανά διαθέσιμο", description: "Αγαπημένο προϊόν επέστρεψε σε απόθεμα.", trigger: "Απόθεμα από 0 σε >0 για προϊόν με ειδοποίηση", marketing: true, sample: () => ({ firstName: "Μαρία", product: PRODUCTS[1], store: "Euronics Αθήνα — Μεσογείων 64" }), render: (d, ctx) => renderEmail(ctx, { subject: `Ξανά διαθέσιμο: ${d.product.brand} ${d.product.title}`, preheader: d.store ? `Και για παραλαβή σε 2 ώρες από ${d.store}` : "", marketing: true, blocks: [h1("Επέστρεψε!"), p(`Γεια σου ${esc(d.firstName)}, το <b>${esc(d.product.brand)} ${esc(d.product.title)}</b> είναι ξανά διαθέσιμο${d.store ? ` — και για παραλαβή σε 2 ώρες από ${esc(d.store)}` : ""}.`), products(ctx, [d.product]), button("Αγόρασέ το τώρα", `${ctx.baseUrl}${d.product.href}`)] }) }),
  /* ---------- loyalty ---------- */
  t<{ firstName: string; points: number; balance: number; reason: string }>({ key: "loyalty-points", group: "loyalty", name: "Κέρδισες πόντους", description: "Μετά από παραγγελία, αξιολόγηση ή σύσταση.", trigger: "Νέα εγγραφή πόντων με θετικό πρόσημο", marketing: true, sample: () => ({ firstName: "Μαρία", points: 517, balance: 1757, reason: "την παραγγελία EUR-20260904-0417" }), render: (d, ctx) => renderEmail(ctx, { subject: `+${d.points} πόντοι για σένα`, preheader: `Υπόλοιπο ${d.balance.toLocaleString("el-GR")} πόντοι`, marketing: true, blocks: [h1(`+${d.points} πόντοι!`), p(`Γεια σου ${esc(d.firstName)}, κέρδισες <b>${d.points}</b> πόντους για ${esc(d.reason)}. Υπόλοιπο: <b>${d.balance.toLocaleString("el-GR")}</b> πόντοι = ${money(d.balance / 100)} έκπτωση στην επόμενη αγορά.`), button("Οι πόντοι μου", `${ctx.baseUrl}/logariasmos`, "secondary")] }) }),
  t<{ firstName: string; code: string; until: string }>({ key: "loyalty-birthday", group: "loyalty", name: "Χρόνια πολλά", description: "Δώρο γενεθλίων με κωδικό έκπτωσης.", trigger: "Cron: ημέρα γενεθλίων, με συναίνεση marketing", marketing: true, sample: () => ({ firstName: "Μαρία", code: "BDAY-MARIA-15", until: "30 Απριλίου" }), render: (d, ctx) => renderEmail(ctx, { subject: `Χρόνια πολλά, ${d.firstName}! 🎂`, preheader: "Ένα δώρο από εμάς.", marketing: true, blocks: [h1(`Χρόνια πολλά, ${esc(d.firstName)}!`), p("Για τα γενέθλιά σου, 15 € έκπτωση σε αγορές άνω των 100 €:"), otp(d.code), p(`Ισχύει μέχρι ${esc(d.until)}, online και στα καταστήματα.`), button("Διάλεξε το δώρο σου", `${ctx.baseUrl}/prosfores`), aris(ctx, "Αν θέλεις ιδέες, πες μου τι σου αρέσει.")] }) }),
  /* ---------- gdpr ---------- */
  t<{ firstName: string; number: string; downloadUrl: string; until: string }>({ key: "gdpr-export-ready", group: "gdpr", name: "Τα δεδομένα σου είναι έτοιμα", description: "Παράδοση εξαγωγής δεδομένων (άρθρα 15/20) με ασφαλή σύνδεσμο.", trigger: "Αίτημα GDPR → done (πρόσβαση / φορητότητα)", sample: () => ({ firstName: "Μαρία", number: "GDPR-00003", downloadUrl: "https://www.euronics.gr/api/account/gdpr/download?token=demo", until: "7 ημέρες" }), render: (d, ctx) => renderEmail(ctx, { subject: `Τα δεδομένα σου (${d.number})`, preheader: "Ασφαλής σύνδεσμος λήψης.", blocks: [h1("Τα δεδομένα σου"), p(`Γεια σου ${esc(d.firstName)}, ολοκληρώσαμε το αίτημα <b>${esc(d.number)}</b>. Το αρχείο περιέχει το προφίλ, τις διευθύνσεις, τις παραγγελίες, τις συσκευές, τα αιτήματα service, τους πόντους, τις συναινέσεις και τις συνδέσεις σου.`), button("Λήψη αρχείου (JSON)", d.downloadUrl), note(`Ο σύνδεσμος ισχύει για ${esc(d.until)} και απαιτεί σύνδεση στον λογαριασμό σου.`, "info"), p(`Υπεύθυνος επεξεργασίας: ${esc(ctx.legalName)}. Για οποιαδήποτε απορία, απάντησε σε αυτό το email.`, { muted: true, small: true })] }) }),
  t<{ firstName: string; number: string; when: string }>({ key: "gdpr-erased", group: "gdpr", name: "Επιβεβαίωση διαγραφής", description: "Τελευταίο email: τα προσωπικά δεδομένα διαγράφηκαν / ψευδωνυμοποιήθηκαν.", trigger: "Αίτημα διαγραφής → done", sample: () => ({ firstName: "Μαρία", number: "GDPR-00004", when: new Date().toLocaleDateString("el-GR") }), render: (d, ctx) => renderEmail(ctx, { subject: "Τα δεδομένα σου διαγράφηκαν", preheader: `Αίτημα ${d.number} ολοκληρώθηκε.`, blocks: [h1("Ολοκληρώθηκε"), p(`Γεια σου ${esc(d.firstName)}, στις ${esc(d.when)} διαγράψαμε τα προσωπικά σου δεδομένα σύμφωνα με το αίτημα <b>${esc(d.number)}</b>: όνομα, στοιχεία επικοινωνίας, διευθύνσεις, κάρτες, social logins.`), p("Ό,τι οφείλουμε να κρατήσουμε από τον νόμο (παραστατικά παραγγελιών για 5 έτη) διατηρείται χωρίς σύνδεση με το πρόσωπό σου. Αυτό είναι το τελευταίο μήνυμα που θα λάβεις από εμάς.", { small: true }), p(`Ευχαριστούμε που ήσουν μαζί μας. ${esc(ctx.legalName)}.`, { muted: true, small: true })] }) }),
];

export const templateByKey = (key: string) => EMAIL_TEMPLATES.find((x) => x.key === key);

/** Render a template with data (used by the senders and the admin preview). */
export async function renderTemplate(key: string, data: unknown, ctxExtra: Partial<EmailCtx> = {}) {
  const tpl = templateByKey(key);
  if (!tpl) throw new Error(`unknown email template ${key}`);
  const ctx = await emailCtx(ctxExtra);
  return tpl.render(data, ctx);
}
export const _blocks = { h1, h2, p, button, note, otp, divider, kv, steps, lines, totals, storeCard, products, aris };
export type { Block };
