/**
 * Ελληνικές ονομασίες για το EPREL: ομάδες προϊόντων και τεχνικά πεδία.
 * Χρησιμοποιούνται στη διαχείριση και στη σελίδα προϊόντος· ό,τι δεν είναι
 * εδώ εμφανίζεται με το αγγλικό όνομα του πεδίου, δεν χάνεται.
 */
export const GROUP_NAMES_EL: Record<string, string> = {
  AIR_CONDITIONER: "Κλιματιστικά",
  DOMESTIC_OVEN: "Φούρνοι",
  RANGE_HOOD: "Απορροφητήρες",
  LAMP: "Λαμπτήρες (παλιά κλίμακα)",
  HOUSEHOLD_COMBINED_WASHER_DRIER: "Πλυντήρια-στεγνωτήρια (παλιά κλίμακα)",
  HOUSEHOLD_DISHWASHER: "Πλυντήρια πιάτων (παλιά κλίμακα)",
  HOUSEHOLD_REFRIGERATING_APPLIANCE: "Ψυγεία (παλιά κλίμακα)",
  HOUSEHOLD_TUMBLE_DRIER: "Στεγνωτήρια (παλιά κλίμακα)",
  HOUSEHOLD_WASHING_MACHINE: "Πλυντήρια ρούχων (παλιά κλίμακα)",
  LOCAL_SPACE_HEATER: "Τοπικοί θερμαντήρες χώρου",
  PROFESSIONAL_REFRIGERATOR: "Επαγγελματικά ψυγεία",
  RESIDENTIAL_VENTILATION_UNIT: "Μονάδες αερισμού κατοικιών",
  SOLID_FUEL_BOILER: "Λέβητες στερεών καυσίμων",
  SOLID_FUEL_BOILER_PACKAGE: "Πακέτα λεβήτων στερεών καυσίμων",
  TELEVISION: "Τηλεοράσεις (παλιά κλίμακα)",
  SPACE_HEATER: "Θερμαντήρες χώρου",
  SPACE_HEATER_PACKAGE: "Πακέτα θερμαντήρων χώρου",
  SPACE_HEATER_TEMPERATURE_CONTROL: "Θερμοστάτες θερμαντήρων",
  SPACE_HEATER_SOLAR_DEVICE: "Ηλιακές διατάξεις θερμαντήρων",
  WATER_HEATERS: "Θερμοσίφωνες",
  WATER_HEATER_PACKAGE: "Πακέτα θερμοσιφώνων",
  HOT_WATER_STORAGE_TANK: "Δεξαμενές ζεστού νερού",
  WATER_HEATER_SOLAR_DEVICE: "Ηλιακές διατάξεις θερμοσιφώνων",
  DIRECT_SALES_REFRIGERATION_APPLIANCE: "Ψυγεία άμεσης πώλησης",
  ELECTRONIC_DISPLAY: "Τηλεοράσεις & οθόνες",
  HOUSEHOLD_WASHER_DRYER_2019: "Πλυντήρια-στεγνωτήρια",
  HOUSEHOLD_WASHING_MACHINE_2019: "Πλυντήρια ρούχων",
  LIGHT_SOURCE: "Φωτιστικές πηγές",
  HOUSEHOLD_REFRIGERATING_APPLIANCE_2019: "Ψυγεία & καταψύκτες",
  HOUSEHOLD_DISHWASHER_2019: "Πλυντήρια πιάτων",
  TYRES: "Ελαστικά",
  HOUSEHOLD_TUMBLE_DRYER_2023_2534: "Στεγνωτήρια",
  SMARTPHONE_TABLET_2023_1669: "Smartphones & tablets",
};

/** Ομάδες που πουλά το κατάστημα — προεπιλογή «ενεργές» στον πρώτο συγχρονισμό. */
export const RETAIL_GROUPS = new Set([
  "AIR_CONDITIONER", "DOMESTIC_OVEN", "RANGE_HOOD", "ELECTRONIC_DISPLAY", "HOUSEHOLD_WASHER_DRYER_2019", "HOUSEHOLD_WASHING_MACHINE_2019",
  "LIGHT_SOURCE", "HOUSEHOLD_REFRIGERATING_APPLIANCE_2019", "HOUSEHOLD_DISHWASHER_2019", "HOUSEHOLD_TUMBLE_DRYER_2023_2534", "SMARTPHONE_TABLET_2023_1669",
  "WATER_HEATERS", "LOCAL_SPACE_HEATER",
]);

export interface FieldDef { label: string; unit?: string; kind?: "bool" | "date" | "list" }

/** Κοινά και ανά ομάδα πεδία. Τα κλειδιά είναι ακριβώς όπως στο API. */
export const FIELDS_EL: Record<string, FieldDef> = {
  modelIdentifier: { label: "Κωδικός μοντέλου" },
  supplierOrTrademark: { label: "Μάρκα" },
  trademarkOwner: { label: "Κάτοχος σήματος" },
  energyClass: { label: "Ενεργειακή κλάση" },
  energyClassSDR: { label: "Ενεργειακή κλάση (SDR)" },
  energyClassHDR: { label: "Ενεργειακή κλάση (HDR)" },
  energyClassWash: { label: "Ενεργειακή κλάση (πλύση)" },
  energyClassWashAndDry: { label: "Ενεργειακή κλάση (πλύση & στέγνωμα)" },
  coolingEnergyClass: { label: "Ενεργειακή κλάση ψύξης" },
  heatingEnergyClass: { label: "Ενεργειακή κλάση θέρμανσης" },
  energyEfficiencyIndex: { label: "Δείκτης ενεργειακής απόδοσης" },
  energyConsAnnual: { label: "Ετήσια κατανάλωση", unit: "kWh/έτος" },
  energyConsAnnualV2: { label: "Ετήσια κατανάλωση", unit: "kWh/έτος" },
  energyAnnual: { label: "Ετήσια κατανάλωση", unit: "kWh/έτος" },
  energyConsPerCycle: { label: "Κατανάλωση ανά κύκλο", unit: "kWh" },
  energyConsPer100Cycle: { label: "Κατανάλωση ανά 100 κύκλους", unit: "kWh" },
  energyCons: { label: "Κατανάλωση ανά κύκλο", unit: "kWh" },
  energyCons100: { label: "Κατανάλωση ανά 100 κύκλους", unit: "kWh" },
  energyConsDry: { label: "Κατανάλωση ανά 100 κύκλους", unit: "kWh" },
  energyConsumption100Wash: { label: "Κατανάλωση ανά 100 κύκλους (πλύση)", unit: "kWh" },
  energyConsumption100WashAndDry: { label: "Κατανάλωση ανά 100 κύκλους (πλύση & στέγνωμα)", unit: "kWh" },
  energyConsOnMode: { label: "Κατανάλωση σε λειτουργία", unit: "kWh/1000 h" },
  powerOnModeSDR: { label: "Ισχύς σε λειτουργία (SDR)", unit: "W" },
  powerOnModeHDR: { label: "Ισχύς σε λειτουργία (HDR)", unit: "W" },
  powerOnMode: { label: "Ισχύς σε λειτουργία", unit: "W" },
  powerStandby: { label: "Ισχύς σε αναμονή", unit: "W" },
  powerStandbyMode: { label: "Ισχύς σε αναμονή", unit: "W" },
  powerStandbyNetworked: { label: "Ισχύς σε δικτυωμένη αναμονή", unit: "W" },
  powerNetworkStandby: { label: "Ισχύς σε δικτυωμένη αναμονή", unit: "W" },
  powerNetworkedStandby: { label: "Ισχύς σε δικτυωμένη αναμονή", unit: "W" },
  powerOffMode: { label: "Ισχύς εκτός λειτουργίας", unit: "W" },
  powerDelayStart: { label: "Ισχύς με χρονοκαθυστέρηση", unit: "W" },
  noise: { label: "Θόρυβος", unit: "dB(A)" },
  noiseClass: { label: "Κλάση θορύβου" },
  indoorSoundPowerCooling: { label: "Θόρυβος εσωτερικής μονάδας (ψύξη)", unit: "dB(A)" },
  outdoorSoundPowerCooling: { label: "Θόρυβος εξωτερικής μονάδας (ψύξη)", unit: "dB(A)" },
  indoorSoundPowerHeating: { label: "Θόρυβος εσωτερικής μονάδας (θέρμανση)", unit: "dB(A)" },
  outdoorSoundPowerHeating: { label: "Θόρυβος εξωτερικής μονάδας (θέρμανση)", unit: "dB(A)" },
  dimensionWidth: { label: "Πλάτος", unit: "cm" },
  dimensionHeight: { label: "Ύψος", unit: "cm" },
  dimensionDepth: { label: "Βάθος", unit: "cm" },
  guaranteeDuration: { label: "Εγγύηση", unit: "μήνες" },
  guranteeDuration: { label: "Εγγύηση", unit: "μήνες" },
  ratedCapacity: { label: "Χωρητικότητα", unit: "kg" },
  ratedCapacityWash: { label: "Χωρητικότητα πλύσης", unit: "kg" },
  ratedCapacityWashAndDry: { label: "Χωρητικότητα πλύσης & στεγνώματος", unit: "kg" },
  spinSpeedRated: { label: "Στροφές στυψίματος", unit: "σ.α.λ." },
  spinClass: { label: "Κλάση στυψίματος" },
  waterCons: { label: "Κατανάλωση νερού ανά κύκλο", unit: "L" },
  waterConsumptionWash: { label: "Κατανάλωση νερού (πλύση)", unit: "L" },
  programmeDurationRated: { label: "Διάρκεια προγράμματος eco", unit: "λεπτά" },
  programmeDuration: { label: "Διάρκεια προγράμματος eco", unit: "λεπτά" },
  programDurationRated: { label: "Διάρκεια προγράμματος", unit: "λεπτά" },
  washingEfficiencyIndexV2: { label: "Δείκτης απόδοσης πλύσης" },
  rinsingEffectiveness: { label: "Αποτελεσματικότητα ξεβγάλματος", unit: "g/kg" },
  moisture: { label: "Υπολειπόμενη υγρασία", unit: "%" },
  cleaningPerformanceIndexV2: { label: "Δείκτης απόδοσης καθαρισμού" },
  dryingPerformanceIndexV2: { label: "Δείκτης απόδοσης στεγνώματος" },
  condensationEfficiencyClass: { label: "Κλάση απόδοσης συμπύκνωσης" },
  technology: { label: "Τεχνολογία" },
  type: { label: "Τύπος" },
  designType: { label: "Τύπος σχεδίασης" },
  applianceType: { label: "Τύπος συσκευής" },
  totalVolume: { label: "Συνολικός όγκος", unit: "L" },
  capRefrNet: { label: "Καθαρός όγκος συντήρησης", unit: "L" },
  capFreezeNet: { label: "Καθαρός όγκος κατάψυξης", unit: "L" },
  capBottles: { label: "Χωρητικότητα φιαλών" },
  numberCompartments: { label: "Θάλαμοι" },
  climateClassSN: { label: "Κλιματική κλάση SN", kind: "bool" },
  climateClassN: { label: "Κλιματική κλάση N", kind: "bool" },
  climateClassST: { label: "Κλιματική κλάση ST", kind: "bool" },
  climateClassT: { label: "Κλιματική κλάση T", kind: "bool" },
  fastFreeze: { label: "Ταχεία κατάψυξη", kind: "bool" },
  lowNoiseAppliance: { label: "Χαμηλού θορύβου", kind: "bool" },
  diagonalCm: { label: "Διαγώνιος", unit: "cm" },
  diagonalInch: { label: "Διαγώνιος", unit: "″" },
  resolutionHorizontalPixels: { label: "Ανάλυση οριζόντια", unit: "px" },
  resolutionVerticalPixels: { label: "Ανάλυση κάθετη", unit: "px" },
  panelTechnology: { label: "Τεχνολογία πάνελ" },
  visibleArea: { label: "Ορατή επιφάνεια", unit: "dm²" },
  frequencyRate: { label: "Συχνότητα ανανέωσης", unit: "Hz" },
  autoBrightnessControlAvailable: { label: "Αυτόματη ρύθμιση φωτεινότητας", kind: "bool" },
  minGuaranteedSupportYears: { label: "Ελάχιστη υποστήριξη", unit: "έτη" },
  minAvailabilitySparePartsYears: { label: "Διαθεσιμότητα ανταλλακτικών", unit: "έτη" },
  minAvailabilitySoftwareUpdatesYears: { label: "Ενημερώσεις λογισμικού", unit: "έτη" },
  minYearsSoftwareUpdates: { label: "Ενημερώσεις λογισμικού", unit: "έτη" },
  coolingDesignLoad: { label: "Φορτίο σχεδιασμού ψύξης", unit: "kW" },
  heatingDesignLoad: { label: "Φορτίο σχεδιασμού θέρμανσης", unit: "kW" },
  refrigerantName: { label: "Ψυκτικό μέσο" },
  refrigerantGwp: { label: "GWP ψυκτικού" },
  ductedType: { label: "Με αεραγωγούς", kind: "bool" },
  functionType: { label: "Λειτουργία" },
  numberIndoorUnits: { label: "Εσωτερικές μονάδες" },
  luminousFlux: { label: "Φωτεινή ροή", unit: "lm" },
  correlatedColourTemp: { label: "Θερμοκρασία χρώματος", unit: "K" },
  colourRenderingIndex: { label: "Δείκτης χρωματικής απόδοσης (CRI)" },
  beamAngle: { label: "Γωνία δέσμης", unit: "°" },
  dimmable: { label: "Dimmable", kind: "bool" },
  capType: { label: "Κάλυκας" },
  lightingTechnology: { label: "Τεχνολογία φωτισμού" },
  equivalentPower: { label: "Ισοδύναμη ισχύς", unit: "W" },
  airFlowMax: { label: "Μέγιστη παροχή αέρα", unit: "m³/h" },
  airFlowBoost: { label: "Παροχή αέρα boost", unit: "m³/h" },
  soundPowerMax: { label: "Θόρυβος μέγιστος", unit: "dB(A)" },
  fluidDynamicEfficiencyClass: { label: "Κλάση ρευστοδυναμικής απόδοσης" },
  lightingEfficiencyClass: { label: "Κλάση απόδοσης φωτισμού" },
  greaseFilteringEfficiencyClass: { label: "Κλάση φιλτραρίσματος λιπών" },
  numberCavities: { label: "Θάλαμοι φούρνου" },
  repairabilityClass: { label: "Κλάση επισκευασιμότητας" },
  repairabilityIndex: { label: "Δείκτης επισκευασιμότητας" },
  batteryEnduranceInCycles: { label: "Αντοχή μπαταρίας", unit: "κύκλοι" },
  batteryEndurancePerCycleInHours: { label: "Αυτονομία ανά φόρτιση", unit: "ώρες" },
  ratedBatteryCapacity: { label: "Χωρητικότητα μπαταρίας", unit: "mAh" },
  batteryUserReplaceable: { label: "Μπαταρία αντικαταστάσιμη από χρήστη", kind: "bool" },
  ingressProtectionRating: { label: "Προστασία IP" },
  repeatedFreeFallReliabilityClass: { label: "Κλάση αντοχής σε πτώσεις" },
  screenScratchResistance: { label: "Αντοχή οθόνης σε γρατζουνιές" },
  operatingSystem: { label: "Λειτουργικό" },
  deviceType: { label: "Τύπος συσκευής" },
  isFoldable: { label: "Αναδιπλούμενο", kind: "bool" },
  declaredLoadProfileType: { label: "Προφίλ φορτίου" },
  declaredLoadProfileWaterHeatingEfficiency: { label: "Απόδοση θέρμανσης νερού", unit: "%" },
  declaredLoadProfileWaterHeatingAnnualElectricityCons: { label: "Ετήσια κατανάλωση ρεύματος", unit: "kWh/έτος" },
  isEnergySmartAppliance: { label: "Έξυπνη ενεργειακά συσκευή", kind: "bool" },
  ecoLabel: { label: "Οικολογικό σήμα EU", kind: "bool" },
  webLinkSupplier: { label: "Ιστοσελίδα προμηθευτή" },
  webLinkManufacturer: { label: "Ιστοσελίδα κατασκευαστή" },
  webLinkRepairInstructions: { label: "Οδηγίες επισκευής" },
  webLinkSparePartsAvailability: { label: "Διαθεσιμότητα ανταλλακτικών" },
  onMarketStartDateTS: { label: "Στην αγορά από", kind: "date" },
  onMarketEndDateTS: { label: "Στην αγορά έως", kind: "date" },
};

/** Πεδία διαχείρισης του EPREL που δεν λένε τίποτα στον πελάτη. */
export const HIDDEN_FIELDS = new Set([
  "eprelRegistrationNumber", "productGroup", "implementingAct", "organisation", "contactDetails", "contactId", "status", "blocked", "versionId", "versionNumber", "lastVersion",
  "productModelCoreId", "energyLabelId", "trademarkId", "orgVerificationStatus", "trademarkVerificationStatus", "registrantNature", "visibleToUkMsa", "formType",
  "uploadedLabels", "generatedLabels", "allowEprelLabelGeneration", "importedOn", "exportDateTS", "publishedOnDate", "publishedOnDateTS", "firstPublicationDate", "firstPublicationDateTS",
  "onMarketStartDate", "onMarketEndDate", "onMarketFirstStartDate", "onMarketFirstStartDateTS", "energyClassImage", "energyClassImageWithScale", "energyClassRange",
  "availabilityInEUEEACountries", "modelAvailabilityInCountries", "modelAvailabilityInEUEEACountries", "modelAvailabilityInOtherCountries", "additionalDetails", "additionalInfo", "additionalInfos",
  "languageSpecifics",
]);
