#!/usr/bin/env python3
"""Semi-automatic copy extraction for the CMS.
Usage: python3 scripts/extract-copy.py <file.tsx> <namespace> [--apply]
Finds Greek JSX text nodes and simple string attributes (placeholder, aria-label,
alt, title, label) and replaces them with {c.key}; appends the entries to
lib/cms/copy.generated.ts under the namespace. Prints a report; --apply writes."""
import re, sys, json, unicodedata, os

path, ns = sys.argv[1], sys.argv[2]
apply = "--apply" in sys.argv
src = open(path).read()
GREEK = re.compile(r"[Α-Ωα-ωΆ-Ώά-ώΐΰϊϋ]")
TRANS = {"α":"a","β":"v","γ":"g","δ":"d","ε":"e","ζ":"z","η":"i","θ":"th","ι":"i","κ":"k","λ":"l","μ":"m","ν":"n","ξ":"x","ο":"o","π":"p","ρ":"r","σ":"s","ς":"s","τ":"t","υ":"y","φ":"f","χ":"ch","ψ":"ps","ω":"o"}
def key(text):
    t = unicodedata.normalize("NFD", text.lower())
    t = "".join(ch for ch in t if unicodedata.category(ch) != "Mn")
    t = "".join(TRANS.get(ch, ch) for ch in t)
    words = re.findall(r"[a-z0-9]+", t)[:4]
    k = "_".join(words) or "text"
    return k if not k[0].isdigit() else "t_" + k
entries = {}
used = set()
def mk(text):
    k = key(text)
    base, n = k, 2
    while k in used and entries.get(k) != text:
        k = f"{base}_{n}"; n += 1
    used.add(k); entries[k] = text
    return k
out = src
# 1. JSX text nodes: >  text  <   (no braces, contains Greek, not inside a template literal line)
def repl_text(m):
    lead, text, trail = m.group(1), m.group(2), m.group(3)
    t = text.strip()
    if not GREEK.search(t) or len(t) < 2 or "`" in t: return m.group(0)
    if re.search(r'[;()=]|\bconst\b|\breturn\b|\bimport\b|\|\s*\w', text): return m.group(0)
    k = mk(t)
    return f">{lead}{{c.{k}}}{trail}<"
out = re.sub(r">(\s*)([^<>{}`]*?)(\s*)<", repl_text, out)
# 2. attributes
def repl_attr(m):
    name, text = m.group(1), m.group(2)
    if not GREEK.search(text): return m.group(0)
    k = mk(text)
    return f"{name}={{c.{k}}}"
out = re.sub(r'\b(placeholder|aria-label|alt|title)="([^"{}`]+)"', repl_attr, out)
changed = out != src
print(f"{path}: {len(entries)} strings")
if apply and changed:
    # inject hook/import
    imp = 'import { copyOf } from "@/lib/cms/copy";'
    lines = out.split("\n")
    if imp not in out:
        last = max(i for i, l in enumerate(lines) if l.startswith("import "))
        lines.insert(last + 1, imp)
    if f'const c = copyOf("{ns}");' not in out:
        last = max(i for i, l in enumerate(lines) if l.startswith("import "))
        j = last
        while j + 1 < len(lines) and not lines[j].rstrip().endswith(";"): j += 1
        lines.insert(j + 1, f'\nconst c = copyOf("{ns}");')
    out = "\n".join(lines)
    open(path, "w").write(out)
    gen = "lib/cms/copy.generated.ts"
    data = {}
    if os.path.exists(gen):
        m = re.search(r"= (\{.*\}) as const", open(gen).read(), re.S)
        if m: data = json.loads(m.group(1))
    data[ns] = {**data.get(ns, {}), **entries}
    open(gen, "w").write("// Generated by scripts/extract-copy.py — UI copy per component namespace (CMS «Copy» collection).\nexport const generatedCopy = " + json.dumps(data, ensure_ascii=False, indent=2) + " as const;\n")
    print("applied")
