/**
 * Ανθρώπινα ονόματα για τις ομάδες κειμένων UI και πού εμφανίζονται — για την οθόνη Περιεχόμενο → Κείμενα UI.
 * area: ενότητα ομαδοποίησης · href: σελίδα όπου το βλέπεις (για «Δες το στο site»).
 */
export type CopyMeta = { label: string; area: string; where: string; href?: string };

const A = { buy: "Αγορά & καλάθι", product: "Σελίδα προϊόντος", list: "Κατάλογος & αναζήτηση", account: "Λογαριασμός πελάτη", home: "Αρχική & ζώνες", site: "Γενικά στοιχεία site", aris: "Ερμής (σύμβουλος)", service: "Καταστήματα & εξυπηρέτηση" };

export const COPY_META: Record<string, CopyMeta> = {
  checkout: { label: "Ολοκλήρωση αγοράς (checkout)", area: A.buy, where: "Βήματα στοιχείων, παράδοσης και πληρωμής", href: "/checkout" },
  cart: { label: "Καλάθι", area: A.buy, where: "Σελίδα καλαθιού", href: "/kalathi" },
  miniCart: { label: "Μικρό καλάθι (πλαϊνό)", area: A.buy, where: "Ανοίγει όταν προσθέτεις προϊόν" },
  quickBuy: { label: "Γρήγορη αγορά", area: A.buy, where: "Αγορά με 1 κλικ" },
  orderSuccess: { label: "Επιβεβαίωση παραγγελίας", area: A.buy, where: "Σελίδα «Ευχαριστούμε»" },
  stepper: { label: "Βήματα αγοράς", area: A.buy, where: "Ένδειξη βημάτων στο checkout" },
  wallet: { label: "Πληρωμή με wallet", area: A.buy, where: "Apple Pay / Google Pay στο checkout" },
  giftCard: { label: "Δωροκάρτες", area: A.buy, where: "Σελίδα δωροκαρτών", href: "/kartes-dorou" },
  buybox: { label: "Κουτί αγοράς", area: A.product, where: "Τιμή, δόσεις και κουμπιά αγοράς στο προϊόν" },
  productHeader: { label: "Κεφαλίδα προϊόντος", area: A.product, where: "Τίτλος και διαδρομή στο προϊόν" },
  gallery: { label: "Φωτογραφίες προϊόντος", area: A.product, where: "Gallery στο προϊόν" },
  specs: { label: "Τεχνικά χαρακτηριστικά", area: A.product, where: "Πίνακας χαρακτηριστικών" },
  reviews: { label: "Αξιολογήσεις", area: A.product, where: "Αξιολογήσεις πελατών" },
  questions: { label: "Ερωτήσεις & απαντήσεις", area: A.product, where: "Ερωτήσεις για το προϊόν" },
  sectionNav: { label: "Μενού ενοτήτων προϊόντος", area: A.product, where: "Σταθερό μενού ενοτήτων" },
  stickyBar: { label: "Σταθερή μπάρα προϊόντος", area: A.product, where: "Μπάρα αγοράς κατά την κύλιση" },
  servicesDelivery: { label: "Υπηρεσίες & παράδοση", area: A.product, where: "Επιλογές παράδοσης στο προϊόν" },
  energy: { label: "Κόστος ρεύματος", area: A.product, where: "«Ρεύμα σε ευρώ»" },
  energyChip: { label: "Ενεργειακή ετικέτα", area: A.product, where: "Σήμα ενεργειακής κλάσης" },
  fit: { label: "Χωράει στον χώρο σου", area: A.product, where: "Έλεγχος διαστάσεων" },
  ar: { label: "AR · δες το στον χώρο σου", area: A.product, where: "Παράθυρο AR" },
  compareVerdict: { label: "Σύγκριση · σύμβουλος", area: A.product, where: "Πρόταση στη σύγκριση" },
  compareSimilar: { label: "Σύγκριση με παρόμοια", area: A.product, where: "Παρόμοια προϊόντα" },
  recentlyViewed: { label: "Είδες πρόσφατα", area: A.product, where: "Λωρίδα πρόσφατων" },
  deviceWallet: { label: "Οι συσκευές μου", area: A.account, where: "Εγγυήσεις συσκευών" },
  productCard: { label: "Κάρτα προϊόντος", area: A.list, where: "Κάρτες σε λίστες και ζώνες" },
  productRow: { label: "Γραμμή προϊόντος", area: A.list, where: "Προβολή λίστας" },
  productGrid: { label: "Πλέγμα προϊόντων", area: A.list, where: "Λίστες προϊόντων" },
  quickView: { label: "Γρήγορη προβολή", area: A.list, where: "Παράθυρο γρήγορης προβολής" },
  facets: { label: "Φίλτρα", area: A.list, where: "Φίλτρα στις λίστες" },
  sortBar: { label: "Ταξινόμηση", area: A.list, where: "Ταξινόμηση στις λίστες" },
  pagination: { label: "Σελιδοποίηση", area: A.list, where: "Επόμενη / προηγούμενη σελίδα" },
  search: { label: "Αναζήτηση", area: A.list, where: "Πεδίο αναζήτησης και προτάσεις" },
  compare: { label: "Σύγκριση", area: A.list, where: "Σελίδα σύγκρισης", href: "/sygkrisi" },
  compareTray: { label: "Μπάρα σύγκρισης", area: A.list, where: "Κάτω μπάρα επιλεγμένων για σύγκριση" },
  compareStacked: { label: "Σύγκριση σε κινητό", area: A.list, where: "Σύγκριση σε στενή οθόνη" },
  smartGuide: { label: "Έξυπνος οδηγός αγοράς", area: A.list, where: "Ερωτήσεις του οδηγού", href: "/odigos-agoras" },
  snap: { label: "Snap & Find", area: A.list, where: "Αναζήτηση με φωτογραφία" },
  wishlist: { label: "Λίστα επιθυμιών", area: A.account, where: "Κουμπί λίστας" },
  wishlistGrid: { label: "Λίστα επιθυμιών (σελίδα)", area: A.account, where: "Σελίδα λίστας", href: "/lista" },
  profile: { label: "Προφίλ", area: A.account, where: "Στοιχεία λογαριασμού", href: "/logariasmos" },
  auth: { label: "Σύνδεση / εγγραφή", area: A.account, where: "Φόρμες σύνδεσης και εγγραφής", href: "/syndesi" },
  accountNav: { label: "Μενού λογαριασμού", area: A.account, where: "Πλαϊνό μενού λογαριασμού" },
  orderTimeline: { label: "Πορεία παραγγελίας", area: A.account, where: "Εντοπισμός παραγγελίας" },
  returnForm: { label: "Επιστροφή προϊόντος", area: A.account, where: "Φόρμα επιστροφής" },
  serviceRequest: { label: "Αίτημα service", area: A.account, where: "Φόρμα service" },
  consents: { label: "Συγκαταθέσεις", area: A.account, where: "Προτιμήσεις επικοινωνίας" },
  mySpace: { label: "Ο χώρος μου", area: A.account, where: "Διαστάσεις χώρων του πελάτη" },
  answers: { label: "Γρήγορες απαντήσεις", area: A.aris, where: "Απαντήσεις του Ερμή" },
  advisorOrb: { label: "Κουμπί Ερμή", area: A.aris, where: "Στρογγυλό κουμπί του Ερμή" },
  greeting: { label: "Χαιρετισμός Ερμή", area: A.aris, where: "Μήνυμα καλωσορίσματος" },
  exitIntent: { label: "Πριν φύγεις", area: A.aris, where: "Μήνυμα όταν ο επισκέπτης πάει να φύγει" },
  hero: { label: "Hero αρχικής", area: A.home, where: "Καμπάνιες στην κορυφή", href: "/" },
  bento: { label: "Bento αρχικής", area: A.home, where: "Πλακίδια αρχικής", href: "/" },
  ticker: { label: "Κυλιόμενα μηνύματα", area: A.home, where: "Λωρίδα μηνυμάτων", href: "/" },
  dealTile: { label: "Προσφορά ημέρας", area: A.home, where: "Κάρτα προσφοράς ημέρας", href: "/" },
  servicesTile: { label: "Πλακίδιο υπηρεσιών", area: A.home, where: "Αρχική", href: "/" },
  storeTile: { label: "Πλακίδιο καταστήματος", area: A.home, where: "Αρχική", href: "/" },
  storeFinder: { label: "Εύρεση καταστήματος", area: A.home, where: "Ζώνη καταστημάτων", href: "/" },
  newsletter: { label: "Newsletter", area: A.home, where: "Εγγραφή στο newsletter", href: "/" },
  guidesBand: { label: "Οδηγοί (ζώνη)", area: A.home, where: "Ζώνη οδηγών", href: "/" },
  smartGuidesBand: { label: "Έξυπνοι οδηγοί (ζώνη)", area: A.home, where: "Ζώνη έξυπνων οδηγών", href: "/" },
  newsBand: { label: "Νέα (ζώνη)", area: A.home, where: "Ζώνη νέων", href: "/" },
  newsCard: { label: "Κάρτα νέου", area: A.home, where: "Κάρτες νέων", href: "/nea" },
  carousel: { label: "Carousel", area: A.home, where: "Κουμπιά κύλισης σε λωρίδες" },
  brandHero: { label: "Σελίδα μάρκας · hero", area: A.home, where: "Κορυφή σελίδας μάρκας", href: "/brands/lg" },
  brandBlocks: { label: "Σελίδα μάρκας · ενότητες", area: A.home, where: "Ενότητες σελίδας μάρκας", href: "/brands/lg" },
  brandTiles: { label: "Σελίδες μαρκών (λίστα)", area: A.home, where: "Κάρτες στο /brands", href: "/brands" },
  footer: { label: "Υποσέλιδο", area: A.site, where: "Κάτω μέρος κάθε σελίδας" },
  megaNav: { label: "Κεντρικό μενού", area: A.site, where: "Μενού κατηγοριών" },
  mobileMenu: { label: "Μενού κινητού", area: A.site, where: "Μενού σε κινητό" },
  breadcrumbs: { label: "Διαδρομή (breadcrumbs)", area: A.site, where: "Πάνω από τον τίτλο κάθε σελίδας" },
  cookies: { label: "Cookies", area: A.site, where: "Μπάνερ συγκατάθεσης cookies" },
  policy: { label: "Σελίδες πολιτικής", area: A.site, where: "Όροι, απόρρητο κ.λπ.", href: "/oroi-chrisis" },
  contact: { label: "Επικοινωνία", area: A.service, where: "Φόρμα επικοινωνίας", href: "/epikoinonia" },
  handoff: { label: "Συνέχεια στο κατάστημα", area: A.service, where: "Παραλαβή / βοήθεια από κατάστημα" },
  nearestStore: { label: "Πλησιέστερο κατάστημα", area: A.service, where: "Κάρτα πλησιέστερου καταστήματος", href: "/katastimata" },
};

export const metaOf = (ns: string): CopyMeta => COPY_META[ns] ?? { label: ns, area: "Άλλα", where: "" };
