// Generated by scripts/extract-copy.py — UI copy per component namespace (CMS «Copy» collection).
export const generatedCopy = {
  "checkout": {
    "fortosi": "Φόρτωση…",
    "to_kalathi_soy_einai": "Το καλάθι σου είναι άδειο.",
    "des_ta_proionta": "Δες τα προϊόντα",
    "grigori_oloklirosi": "Γρήγορη ολοκλήρωση",
    "dieythynsi_pliromi_apo_to": "Διεύθυνση & πληρωμή από το wallet σου",
    "i_symplirose_ta_stoicheia": "ή συμπλήρωσε τα στοιχεία σου",
    "syndesi_gia_aytomati_symplirosi": "Σύνδεση για αυτόματη συμπλήρωση, ή συνέχισε ως επισκέπτης.",
    "echeis_logariasmo": "Έχεις λογαριασμό;",
    "katastima_paralavis": "Κατάστημα παραλαβής",
    "etoimi_se_2_ores": "Έτοιμη σε 2 ώρες.",
    "nomos": "Νομός",
    "protimisi_oras": "Προτίμηση ώρας",
    "o_technikos_toy_katastimatos": "Ο τεχνικός του καταστήματος σε καλεί εντός 24 ωρών για την ακριβή ημέρα.",
    "paralavi_palias_syskeyis_gia": "Παραλαβή παλιάς συσκευής για ανακύκλωση — δωρεάν.",
    "tin_pairnoyme_kata_tin": "Την παίρνουμε κατά την παράδοση (ΑΗΗΕ, Οδηγία 2012/19/ΕΕ).",
    "scholia_gia_ton_dianomea": "Σχόλια για τον διανομέα",
    "proairetika": "(προαιρετικά)",
    "vrethike_sto_mitroo_aade": "Βρέθηκε στο μητρώο ΑΑΔΕ — τα στοιχεία συμπληρώθηκαν.",
    "piso_sto_kalathi": "← Πίσω στο καλάθι",
    "synecheia_stin_pliromi": "Συνέχεια στην πληρωμή →",
    "arithmos_kartas": "Αριθμός κάρτας",
    "lixi": "Λήξη",
    "atokes_doseis": "Άτοκες δόσεις",
    "ta_stoicheia_kartas_den": "Τα στοιχεία κάρτας δεν αποθηκεύονται στη Euronics. Η πληρωμή γίνεται στον πάροχο με 3D Secure.",
    "tha_metafertheis_sto_asfales": "Θα μεταφερθείς στο ασφαλές περιβάλλον της Eurobank για online αίτηση με τους κωδικούς e-banking σου. Έγκριση σε λίγα λεπτά. Η παραγγελία εκτελείται μετά την έγκριση.",
    "oi_logariasmoi_ethniki_peiraios": "Οι λογαριασμοί (Εθνική, Πειραιώς, Eurobank, Alpha) θα σου σταλούν με το email επιβεβαίωσης. Αιτιολογία: ο αριθμός παραγγελίας. Το απόθεμα κρατείται 48 ώρες.",
    "tha_anoixei_to_mobile": "Θα ανοίξει το mobile banking σου με προσυμπληρωμένο ποσό και αιτιολογία. Η παραγγελία επιβεβαιώνεται αμέσως.",
    "logariasmos_sygkatatheseis": "Λογαριασμός & συγκαταθέσεις",
    "dimioyrgise_logariasmo": "Δημιούργησε λογαριασμό",
    "kodikos": "Κωδικός",
    "toylachiston_8_charaktires": "(τουλάχιστον 8 χαρακτήρες)",
    "thelo_prosfores_me_email": "Θέλω προσφορές με email. Ξεχωριστή συγκατάθεση, την αφαιρείς όποτε θες.",
    "oroys_chrisis": "όρους χρήσης",
    "politiki_aporritoy": "πολιτική απορρήτου",
    "mporo_na_epistrepso_o": ". Μπορώ να επιστρέψω ό,τι αγοράσω μέσα σε 14 ημέρες, χωρίς αιτιολογία.",
    "stoicheia_paradosi": "← Στοιχεία & παράδοση",
    "i_paraggelia_soy": "Η παραγγελία σου",
    "efarmogi": "Εφαρμογή",
    "synolo": "Σύνολο",
    "proairetika_2": "προαιρετικά",
    "allagi": "Αλλαγή",
    "pliromi_me_apple_pay": "Πληρωμή με Apple Pay",
    "pliromi_me_google_pay": "Πληρωμή με Google Pay",
    "pliromi_me_revolut_pay": "Πληρωμή με Revolut Pay",
    "stoicheia_epikoinonias": "Στοιχεία επικοινωνίας",
    "paradosi": "Παράδοση",
    "p_ch_koydoyni_ores": "π.χ. κουδούνι, ώρες παρουσίας",
    "apodeixi_i_timologio": "Απόδειξη ή τιμολόγιο",
    "pliromi": "Πληρωμή",
    "synopsi_paraggelias": "Σύνοψη παραγγελίας",
    "koyponi_i_karta_doroy": "Κουπόνι ή κάρτα δώρου",
    "koyponi": "Κουπόνι"
  },
  "cart": {
    "fortosi_kalathioy": "Φόρτωση καλαθιού…",
    "kalathi": "Καλάθι",
    "to_kalathi_soy_einai": "Το καλάθι σου είναι άδειο",
    "des_tis_prosfores_tis": "Δες τις προσφορές της εβδομάδας, ή άσε τον έξυπνο οδηγό να βρει τη σωστή τηλεόραση, υπολογιστή ή κλιματιστικό για σένα.",
    "prosfores_tis_evdomadas": "Προσφορές της εβδομάδας",
    "exypnos_odigos_agoras": "Έξυπνος οδηγός αγοράς",
    "dimofili_ayti_tin_evdomada": "Δημοφιλή αυτή την εβδομάδα",
    "adeiasma": "Άδειασμα",
    "prosthese_akomi": "Πρόσθεσε ακόμη",
    "gia_dorean_metaforika": "για δωρεάν μεταφορικά.",
    "kalypse_to": "Κάλυψέ το",
    "afairesi": "Αφαίρεση",
    "synechise_tis_agores": "← Συνέχισε τις αγορές",
    "synopsi": "Σύνοψη",
    "efarmogi": "Εφαρμογή",
    "synolo": "Σύνολο",
    "eos_24_atokes_me": "· έως 24 άτοκες με κάρτα",
    "oloklirosi_agoras": "Ολοκλήρωση αγοράς",
    "asfalis_pliromi_me_3d": "Ασφαλής πληρωμή με 3D Secure",
    "epistrofi_se_350_katastimata": "Επιστροφή σε 350 καταστήματα",
    "mia_apostoli_ena_kostos": "Μία αποστολή, ένα κόστος μεταφορικών",
    "tairiazoyn_me_to_kalathi": "Ταιριάζουν με το καλάθι σου",
    "dimofili": "Δημοφιλή",
    "koyponi_i_karta_doroy": "Κουπόνι ή κάρτα δώρου",
    "koyponi": "Κουπόνι",
    "ligotera": "Λιγότερα",
    "perissotera": "Περισσότερα"
  },
  "buybox": {
    "choris_karta_eurobank": "χωρίς κάρτα · Eurobank",
    "atoka_me_karta": "άτοκα με κάρτα",
    "pos_to_theleis": "Πώς το θέλεις;",
    "sti_dieythynsi_moy": "Στη διεύθυνσή μου",
    "paralavi_apo_katastima": "Παραλαβή από κατάστημα",
    "dorean": "Δωρεάν",
    "metafora_sto_katastima_1": "Μεταφορά στο κατάστημα · 1–3 εργάσιμες",
    "orario": "ωράριο",
    "me_rantevoy_egkatastasi": "Με ραντεβού & εγκατάσταση",
    "apo_60": "από 60 €",
    "technikos_toy_katastimatos_tis": "Τεχνικός του καταστήματος της περιοχής σου, ραντεβού εντός 24 ωρών.",
    "olokliromeni_lysi": "Ολοκληρωμένη λύση",
    "tairiazei_me_ayto_to": "Ταιριάζει με αυτό το προϊόν · μία αποστολή",
    "agora_me_1_klik": "Αγορά με 1 κλικ",
    "eggyisi_2_eti_epistrofi": "Εγγύηση 2 έτη · Επιστροφή μέσα σε 14 ημέρες",
    "agora": "Αγορά",
    "katastima": "Κατάστημα",
    "ligotera": "Λιγότερα",
    "perissotera": "Περισσότερα"
  },
  "orderSuccess": {
    "eycharistoyme_i_paraggelia_soy": "Ευχαριστούμε! Η παραγγελία σου καταχωρήθηκε.",
    "arithmos_paraggelias": "Αριθμός παραγγελίας",
    "ti_ginetai_tora": "Τι γίνεται τώρα",
    "katethese_to_poso_entos": "Κατέθεσε το ποσό εντός 48 ωρών με αιτιολογία τον αριθμό παραγγελίας. Οι λογαριασμοί είναι στο email.",
    "oloklirose_tin_aitisi_sto": "Ολοκλήρωσε την αίτηση στο περιβάλλον της Eurobank· με την έγκριση, η παραγγελία εκτελείται.",
    "paralamvaneis_me_ton_arithmo": "Παραλαμβάνεις με τον αριθμό παραγγελίας και ταυτότητα.",
    "i_paraggelia_etoimazetai_kai": "Η παραγγελία ετοιμάζεται και παραδίδεται στον courier εντός 1 εργάσιμης.",
    "tha_laveis_sms_me": "Θα λάβεις SMS με τον αριθμό αποστολής. Παράδοση σε 1–3 εργάσιμες.",
    "parakoloythisi_paraggelias": "Παρακολούθηση παραγγελίας",
    "stoicheia_paraggelias": "Στοιχεία παραγγελίας",
    "paradosi": "Παράδοση",
    "pliromi": "Πληρωμή",
    "apodeixi_lianikis": "Απόδειξη λιανικής",
    "logariasmos": "Λογαριασμός",
    "des_paraggelies_eggyiseis_kai": "Δες παραγγελίες, εγγυήσεις και επιστροφές σε ένα μέρος",
    "dimioyrgia_logariasmoy": "Δημιουργία λογαριασμού",
    "synopsi": "Σύνοψη",
    "metaforika": "Μεταφορικά",
    "synolo": "Σύνολο",
    "i_synopsi_einai_diathesimi": "Η σύνοψη είναι διαθέσιμη στο email επιβεβαίωσης.",
    "piso_stin_archiki": "Πίσω στην αρχική"
  },
  "miniCart": {
    "prostethike_sto_kalathi": "Προστέθηκε στο καλάθι",
    "to_kalathi_soy_einai": "Το καλάθι σου είναι άδειο.",
    "des_ta_proionta": "Δες τα προϊόντα",
    "akomi": "Ακόμη",
    "gia_dorean_metaforika": "για δωρεάν μεταφορικά.",
    "tairiazei_me_to_kalathi": "Ταιριάζει με το καλάθι σου",
    "prosthiki": "Προσθήκη",
    "proionta_ypiresies": "Προϊόντα & υπηρεσίες",
    "metaforika": "Μεταφορικά",
    "synolo": "Σύνολο",
    "oloklirosi_agoras": "Ολοκλήρωση αγοράς",
    "des_to_kalathi": "Δες το καλάθι",
    "synechise_tis_agores": "Συνέχισε τις αγορές",
    "epistrofi_mesa_se_14": "Επιστροφή μέσα σε 14 ημέρες",
    "paralavi_se_2_ores": "Παραλαβή σε 2 ώρες",
    "kleisimo": "Κλείσιμο",
    "ligotera": "Λιγότερα",
    "perissotera": "Περισσότερα",
    "afairesi": "Αφαίρεση"
  },
  "productCard": {
    "grigori_provoli": "Γρήγορη προβολή",
    "agora_me_1_klik": "Αγορά με 1 κλικ",
    "sto_kalathi": "Στο καλάθι",
    "sygkrisi": "Σύγκριση",
    "prosthiki_sto_kalathi": "Προσθήκη στο καλάθι"
  },
  "quickView": {
    "grigori_provoli": "Γρήγορη προβολή",
    "kleisimo": "Κλείσιμο",
    "choris_karta": "χωρίς κάρτα",
    "atoka_me_karta": "άτοκα με κάρτα",
    "agora_me_1_klik": "Αγορά με 1 κλικ",
    "prosthiki_sto_kalathi": "Προσθήκη στο καλάθι",
    "ligotera": "Λιγότερα",
    "perissotera": "Περισσότερα",
    "lista_epithymion": "Λίστα επιθυμιών",
    "sygkrisi": "Σύγκριση"
  },
  "quickBuy": {
    "grigori_agora": "Γρήγορη αγορά",
    "kleisimo": "Κλείσιμο",
    "chreonetai_i_karta_soy": "Χρεώνεται η κάρτα σου και η παραγγελία καταχωρείται αμέσως. Η τράπεζά σου θα ζητήσει επιβεβαίωση (3D Secure). Μπορείς να επιστρέψεις το προϊόν μέσα σε 14 ημέρες.",
    "allagi": "αλλαγή"
  },
  "footer": {
    "epikoinonia": "Επικοινωνία",
    "damaskoy_stamati_12_136": "Δαμάσκου Σταμάτη 12, 136 71 Αχαρνές",
    "euronics_2026_mega_electrics": "© euronics 2026 · MEGA ELECTRICS ΑΕΒΕ · ΑΦΜ 998182322 · ΔΟΥ ΦΑΕ Αθηνών · Αρ. μητρώου ΑΗΗΕ —",
    "oi_times_perilamvanoyn_fpa": "Οι τιμές περιλαμβάνουν ΦΠΑ 24%. Τα μεταφορικά υπολογίζονται πριν την οριστικοποίηση της παραγγελίας.",
    "tropoi_pliromis": "Τρόποι πληρωμής"
  },
  "productHeader": {
    "archiki": "Αρχική",
    "prosfora": "Προσφορά",
    "neo": "Νέο",
    "sygkrine_me_paromoia": "Σύγκρινε με παρόμοια →",
    "diadromi": "Διαδρομή"
  },
  "smartGuide": {
    "dialexe_ena_i_perissotera": "Διάλεξε ένα ή περισσότερα",
    "piso": "Πίσω",
    "ti_chreiazesai": "Τι χρειάζεσαι",
    "oi_apantiseis_soy": "Οι απαντήσεις σου",
    "allagi_apantiseon": "Αλλαγή απαντήσεων",
    "apo_tin_archi": "Από την αρχή",
    "ola_ta_montela_me": "Όλα τα μοντέλα με αυτά τα φίλτρα →",
    "enallaktikes_poy_axizei_na": "Εναλλακτικές που αξίζει να δεις",
    "sygkrisi": "Σύγκριση",
    "ektos_proypologismoy": "Εκτός προϋπολογισμού",
    "giati_soy_tairiazei": "Γιατί σου ταιριάζει",
    "ti_na_echeis_ypopsi": "Τι να έχεις υπόψη",
    "agora_me_1_klik": "Αγορά με 1 κλικ",
    "sto_kalathi": "Στο καλάθι",
    "lista_epithymion": "Λίστα επιθυμιών"
  },
  "compare": {
    "den_echeis_epilexei_proionta": "Δεν έχεις επιλέξει προϊόντα για σύγκριση",
    "tsekare_sygkrisi_se_eos": "Τσέκαρε «Σύγκριση» σε έως 4 κάρτες προϊόντων. Τα χαρακτηριστικά ευθυγραμμίζονται αυτόματα.",
    "des_ola_ta_proionta": "Δες όλα τα προϊόντα",
    "mono_oi_diafores": "Μόνο οι διαφορές",
    "prosthese_ki_allo": "πρόσθεσε κι άλλο",
    "fthinotero": "Φθηνότερο",
    "agora_me_1_klik": "Αγορά με 1 κλικ",
    "sto_kalathi": "Στο καλάθι",
    "diathesimotita": "Διαθεσιμότητα",
    "axiologisi": "Αξιολόγηση",
    "diaferei": "διαφέρει",
    "afairesi": "Αφαίρεση"
  },
  "profile": {
    "prosopika_stoicheia": "Προσωπικά στοιχεία",
    "onoma": "Όνομα",
    "eponymo": "Επώνυμο",
    "kinito": "Κινητό",
    "imerominia_gennisis": "Ημερομηνία γέννησης",
    "afm": "ΑΦΜ",
    "apothikeysi": "Αποθήκευση",
    "asfaleia": "Ασφάλεια",
    "trechon_kodikos": "Τρέχων κωδικός",
    "neos_kodikos": "Νέος κωδικός",
    "epanalipsi": "Επανάληψη",
    "epalitheysi_dyo_vimaton": "Επαλήθευση δύο βημάτων",
    "allagi_kodikoy": "Αλλαγή κωδικού",
    "lipsi_dedomenon": "Λήψη δεδομένων",
    "diagrafi_logariasmoy": "Διαγραφή λογαριασμού"
  },
  "auth": {
    "onoma": "Όνομα",
    "eponymo": "Επώνυμο",
    "kinito": "Κινητό",
    "kodikos": "Κωδικός",
    "na_me_thymasai": "Να με θυμάσαι",
    "oroys": "όρους",
    "politiki_aporritoy": "πολιτική απορρήτου",
    "syndesi": "Σύνδεση",
    "tha_laveis_kodiko_epivevaiosis": "Θα λάβεις κωδικό επιβεβαίωσης (OTP)"
  },
  "serviceRequest": {
    "tha_se_kalesei_o": "Θα σε καλέσει ο τεχνικός του καταστήματος μέσα σε 24 ώρες για να κλείσετε ώρα. Θα το βλέπεις εδώ, στα «Ραντεβού & service».",
    "dilosi_vlavis_service": "Δήλωση βλάβης / service",
    "fotografia_vinteo": "Φωτογραφία / βίντεο",
    "protimisi": "Προτίμηση",
    "apostoli_aitimatos": "Αποστολή αιτήματος",
    "p_ch_den_styvei": "π.χ. Δεν στύβει, βγάζει κωδικό E4 στην οθόνη",
    "tropos_exypiretisis": "Τρόπος εξυπηρέτησης"
  },
  "orderTimeline": {
    "anoigma_ston_courier": "Άνοιγμα στον courier"
  },
  "megaNav": {
    "perissotera": "Περισσότερα",
    "dimofili_tora": "Δημοφιλή τώρα",
    "markes": "Μάρκες",
    "agora_me_1_klik": "Αγορά με 1 κλικ",
    "des_to_proion": "Δες το προϊόν",
    "syntoma_proionta_se_ayti": "Σύντομα προϊόντα σε αυτή την κατηγορία.",
    "katigories_proionton": "Κατηγορίες προϊόντων",
    "perissoteres_katigories": "Περισσότερες κατηγορίες",
    "kleisimo_menoy": "Κλείσιμο μενού"
  },
  "snap": {
    "snap_find_me_ton": "Snap & Find · με τον Ερμή",
    "fotografise_tin_palia_soy": "Φωτογράφισε την παλιά σου συσκευή",
    "tin_pinakida_me_to": "Την πινακίδα με το μοντέλο, μέσα στην πόρτα ή πίσω. Διαβάζουμε τον κωδικό στη συσκευή σου, δεν ανεβαίνει πουθενά.",
    "anoixe_tin_kamera_i": "Άνοιξε την κάμερα ή διάλεξε φωτογραφία",
    "diavazo_tin_pinakida": "Διαβάζω την πινακίδα…",
    "i_grapse_ton_kodiko": "Ή γράψε τον κωδικό μοντέλου",
    "den_katafera_na_diavaso": "Δεν κατάφερα να διαβάσω κωδικό. Δοκίμασε πιο κοντά και με φως, ή γράψε το μοντέλο.",
    "vrika_tin_katigoria": "Βρήκα την κατηγορία",
    "kleisimo": "Κλείσιμο",
    "i_fotografia_soy": "Η φωτογραφία σου",
    "i_grapse_to_montelo": "ή γράψε το μοντέλο"
  },
  "deviceWallet": {
    "apomenoyn": "απομένουν",
    "dilosi_vlavis_service": "Δήλωση βλάβης / service",
    "epektasi_se_5_eti": "Επέκταση σε 5 έτη",
    "grammi_kataskeyasti": "Γραμμή κατασκευαστή:",
    "service_euronics_rantevoy_entos": "Service Euronics: ραντεβού εντός 48 ωρών"
  },
  "giftCard": {
    "poso": "Ποσό",
    "paradosi": "Παράδοση",
    "onoma_paralipti": "Όνομα παραλήπτη",
    "schedio": "Σχέδιο",
    "karta_doroy": "Κάρτα δώρου",
    "exargyrosi_online_kai_se": "Εξαργύρωση online και σε 350 καταστήματα · ισχύς 2 έτη"
  },
  "answers": {
    "grigores_apantiseis": "Γρήγορες απαντήσεις",
    "o_ti_tha_rotoyses": "Ό,τι θα ρωτούσες στο κατάστημα",
    "rota_ton_ari": "Ρώτα τον Ερμή:",
    "seo_aeo_geo_gia": "SEO · AEO · GEO για αυτό το προϊόν",
    "ti_ekpempei_i_selida": "— τι εκπέμπει η σελίδα σε μηχανές αναζήτησης, answer engines και AI"
  },
  "mySpace": {
    "o_choros_moy": "Ο χώρος μου",
    "dose_ta_mia_fora": "Δώσε τα μία φορά. Κάθε συσκευή θα σου λέει αν χωράει.",
    "metra_to_katharo_anoigma": "Μέτρα το καθαρό άνοιγμα, όχι την κάσα.",
    "yparchei_asanser": "Υπάρχει ασανσέρ",
    "echo_sygkekrimeni_esochi": "Έχω συγκεκριμένη εσοχή",
    "apothikeysi": "Αποθήκευση",
    "katharisma": "Καθάρισμα",
    "kleisimo": "Κλείσιμο"
  },
  "returnForm": {
    "steilame_odigies_sto_email": "Στείλαμε οδηγίες στο email σου. Μπορείς να παραδώσεις το προϊόν σε οποιοδήποτε κατάστημα Euronics ή να ζητήσεις παραλαβή από courier. Η επιστροφή χρημάτων γίνεται εντός 14 ημερών από την παραλαβή.",
    "paraggelia": "Παραγγελία",
    "proionta_pros_epistrofi": "Προϊόντα προς επιστροφή",
    "logos": "Λόγος",
    "lathos_proion": "Λάθος προϊόν",
    "zimia_sti_metafora": "Ζημιά στη μεταφορά",
    "tropos_epistrofis": "Τρόπος επιστροφής",
    "scholia": "Σχόλια",
    "ypovoli_aitimatos": "Υποβολή αιτήματος"
  },
  "accountNav": {
    "giannis_papadopoylos": "Γιάννης Παπαδόπουλος",
    "aposyndesi": "Αποσύνδεση",
    "logariasmos": "Λογαριασμός"
  },
  "facets": {
    "katharismos_olon": "Καθαρισμός όλων",
    "filtra": "Φίλτρα",
    "katigoria": "Κατηγορία",
    "diathesimotita_prosfores": "Διαθεσιμότητα & προσφορές",
    "timi": "Τιμή",
    "marka": "Μάρκα",
    "energeiaki_klasi": "Ενεργειακή κλάση",
    "elachisti_timi": "Ελάχιστη τιμή",
    "megisti_timi": "Μέγιστη τιμή"
  },
  "servicesDelivery": {
    "ypiresies_paradosi": "Υπηρεσίες & παράδοση",
    "pos_to_pairneis_kai": "Πώς το παίρνεις και τι σε καλύπτει",
    "epiloges_paradosis_gia_ayto": "Επιλογές παράδοσης για αυτό το προϊόν",
    "ypiresies_euronics_gia_ayto": "Υπηρεσίες Euronics για αυτό το προϊόν"
  },
  "contact": {
    "lavame_to_minyma_soy": "Λάβαμε το μήνυμά σου",
    "apantame_entos_1_ergasimis": "Απαντάμε εντός 1 εργάσιμης ημέρας. Για επείγον, κάλεσε στο 210 483 5143.",
    "onomateponymo": "Ονοματεπώνυμο",
    "tilefono": "Τηλέφωνο",
    "thema": "Θέμα",
    "erotisi_gia_paraggelia": "Ερώτηση για παραγγελία",
    "techniki_erotisi_gia_proion": "Τεχνική ερώτηση για προϊόν",
    "service_eggyisi": "Service / εγγύηση",
    "epistrofi": "Επιστροφή",
    "tilefoniki_paraggelia": "Τηλεφωνική παραγγελία",
    "allo": "Άλλο",
    "minyma": "Μήνυμα",
    "apostoli": "Αποστολή"
  },
  "policy": {
    "pigi": "πηγή",
    "exypiretisi": "Εξυπηρέτηση"
  },
  "compareVerdict": {
    "symvoylos_agoras": "Σύμβουλος αγοράς",
    "exigise_moy_ti_diafora": "Εξήγησέ μου τη διαφορά",
    "apo_ta_charaktiristika_toy": "Από τα χαρακτηριστικά του καταλόγου και την εκτίμηση κατανάλωσης · 0,19 €/kWh."
  },
  "reviews": {
    "axiologiseis": "Αξιολογήσεις",
    "grapse_axiologisi": "Γράψε αξιολόγηση",
    "onoma": "Όνομα",
    "vathmologia": "Βαθμολογία",
    "titlos": "Τίτλος",
    "i_gnomi_soy": "Η γνώμη σου",
    "ypovoli": "Υποβολή",
    "eycharistoyme_i_axiologisi_soy": "Ευχαριστούμε. Η αξιολόγησή σου θα δημοσιευθεί μετά από έλεγχο.",
    "den_yparchoyn_akomi_axiologiseis": "Δεν υπάρχουν ακόμη αξιολογήσεις για αυτό το προϊόν.",
    "epivevaiomeni_agora": "Επιβεβαιωμένη αγορά"
  },
  "brandBlocks": {
    "oli_i_seira": "Όλη η σειρά",
    "ypostirixi": "Υποστήριξη"
  },
  "brandHero": {
    "episimos_synergatis_euronics": "Επίσημος συνεργάτης Euronics",
    "ergostasiaki_eggyisi": "Εργοστασιακή εγγύηση",
    "service_antiprosopeias": "Service αντιπροσωπείας",
    "doseis_choris_karta": "Δόσεις χωρίς κάρτα",
    "paralavi_se_2_ores": "Παραλαβή σε 2 ώρες από 350 καταστήματα"
  },
  "wallet": {
    "egine": "Έγινε",
    "i_paraggelia_katachoreitai": "Η παραγγελία καταχωρείται…",
    "epexergasia_pliromis": "Επεξεργασία πληρωμής",
    "allagi": "Αλλαγή",
    "pliromi_se_euronics": "ΠΛΗΡΩΜΗ ΣΕ EURONICS",
    "kleisimo": "Κλείσιμο",
    "akyrosi": "Ακύρωση"
  },
  "fit": {
    "des_an_choraei_ston": "Δες αν χωράει στον χώρο σου"
  },
  "storeTile": {
    "to_katastima_soy": "Το κατάστημά σου",
    "tachydromikos_kodikas_i_poli": "Ταχυδρομικός κώδικας ή πόλη",
    "vres": "Βρες",
    "chrisi_tis_topothesias_moy": "Χρήση της τοποθεσίας μου",
    "tk_i_poli": "ΤΚ ή πόλη"
  },
  "handoff": {
    "to_katastima_soy": "Το κατάστημά σου",
    "mprilaki_afoi_e_e": "ΜΠΡΙΛΑΚΗ ΑΦΟΙ Ε.Ε.",
    "t_3_6_km_anoichto": "3,6 km · ανοιχτό έως 21:00",
    "o_nikos_tha_se": "Ο Νίκος θα σε πάρει σε λίγα λεπτά",
    "entaxei": "Εντάξει",
    "tha_parei_ti_synomilia": "Θα πάρει τη συνομιλία σου:",
    "onoma": "Όνομα",
    "kinito": "Κινητό",
    "na_me_paroyn": "Να με πάρουν",
    "ta_stoicheia_pane_mono": "Τα στοιχεία πάνε μόνο στο κατάστημα, για αυτή την κλήση.",
    "piso": "Πίσω"
  },
  "ar": {
    "ar_se_pragmatiki_klimaka": "AR · σε πραγματική κλίμακα",
    "skanare_me_to_kinito": "Σκάναρε με το κινητό για να το δεις στον χώρο σου.",
    "kleisimo": "Κλείσιμο",
    "qr_gia_anoigma_sto": "QR για άνοιγμα στο κινητό"
  },
  "sortBar": {
    "taxinomisi": "Ταξινόμηση",
    "provoli": "Προβολή",
    "plegma": "Πλέγμα",
    "lista": "Λίστα"
  },
  "compareSimilar": {
    "sygkrisi": "Σύγκριση",
    "sygkrine_me_paromoia_proionta": "Σύγκρινε με παρόμοια προϊόντα",
    "pliris_sygkrisi": "Πλήρης σύγκριση →",
    "ayto_to_proion": "Αυτό το προϊόν",
    "energeiaki_klasi": "Ενεργειακή κλάση",
    "axiologisi": "Αξιολόγηση",
    "diaferei": "διαφέρει"
  },
  "sectionNav": {
    "enotites_proiontos": "Ενότητες προϊόντος"
  },
  "questions": {
    "erotiseis_apantiseis": "Ερωτήσεις & απαντήσεις",
    "perimenei_apantisi_apo_tin": "Περιμένει απάντηση από την ομάδα μας.",
    "lavame_tin_erotisi_soy": "Λάβαμε την ερώτησή σου. Απαντάμε εντός 1 εργάσιμης, με email.",
    "i_erotisi_soy": "Η ερώτησή σου",
    "rotise": "Ρώτησε",
    "rotise_kati_gia_to": "Ρώτησε κάτι για το προϊόν"
  },
  "nearestStore": {
    "odigies": "Οδηγίες"
  },
  "dealTile": {
    "prosfora_imeras": "Προσφορά ημέρας",
    "agora_me_1_klik": "Αγορά με 1 κλικ",
    "prosthiki_sto_kalathi": "Προσθήκη στο καλάθι"
  },
  "servicesTile": {
    "ypiresies": "Υπηρεσίες"
  },
  "storeFinder": {
    "to_diktyo": "Το δίκτυο",
    "ena_einai_dipla_soy": "Ένα είναι δίπλα σου.",
    "apothema_se_pragmatiko_chrono": "Απόθεμα σε πραγματικό χρόνο, παραλαβή σε 2 ώρες, εγκατάσταση από τον τεχνικό της γειτονιάς σου.",
    "tachydromikos_kodikas_i_poli": "Ταχυδρομικός κώδικας ή πόλη",
    "vres": "Βρες",
    "katastima_euronics": "Κατάστημα euronics"
  },
  "newsletter": {
    "mathe_protos_tis_pragmatikes": "Μάθε πρώτος τις πραγματικές πτώσεις τιμών",
    "ena_email_tin_evdomada": "Ένα email την εβδομάδα. Διαγραφή με ένα κλικ, χωρίς ερωτήσεις.",
    "to_email_soy": "Το email σου",
    "eggrafi": "Εγγραφή",
    "politiki_aporritoy": "Πολιτική Απορρήτου"
  },
  "guidesBand": {
    "eikona_arthroy": "εικόνα άρθρου",
    "prota_katalavaineis_meta_agorazeis": "Πρώτα καταλαβαίνεις, μετά αγοράζεις"
  },
  "smartGuidesBand": {
    "exypnos_odigos_agoras": "Έξυπνος οδηγός αγοράς",
    "pes_mas_pos_tha": "Πες μας πώς θα το χρησιμοποιείς. Θα σου πούμε ποιο — και γιατί.",
    "pos_doyleyei": "Πώς δουλεύει →"
  },
  "newsBand": {
    "ti_ginetai_sti_euronics": "Τι γίνεται στη Euronics"
  },
  "exitIntent": {
    "steile": "Στείλε",
    "kleisimo": "Κλείσιμο",
    "to_email_soy_gia": "Το email σου για το καλάθι"
  },
  "advisorOrb": {
    "rota_me": "Ρώτα με",
    "anthropos_apo_to_katastima": "Άνθρωπος από το\n                    κατάστημα",
    "i_erotisi_soy": "Η ερώτησή σου",
    "symvoylos_agoras": "Σύμβουλος αγοράς",
    "kleisimo": "Κλείσιμο",
    "o_symvoylos_grafei": "Ο σύμβουλος γράφει",
    "apostoli": "Αποστολή"
  },
  "search": {
    "katigoria_anazitisis": "Κατηγορία αναζήτησης",
    "katigoria": "Κατηγορία",
    "anazitisi_proionton": "Αναζήτηση προϊόντων",
    "anazitisi": "Αναζήτηση",
    "den_vrethikan_proionta_gia": "Δεν βρέθηκαν προϊόντα για αυτή την περιγραφή.",
    "dokimase_marka_montelo_i": "Δοκίμασε μάρκα, μοντέλο ή κωδικό, ή ρώτησε τον έξυπνο οδηγό αγοράς.",
    "exypnos_odigos_agoras": "Έξυπνος οδηγός αγοράς",
    "proionta": "Προϊόντα",
    "kanena_proion_me_aytoys": "Κανένα προϊόν με αυτούς τους όρους.",
    "katigories": "Κατηγορίες",
    "markes": "Μάρκες",
    "odigoi": "Οδηγοί",
    "prosfates": "Πρόσφατες",
    "katharismos": "Καθαρισμός",
    "dimofileis_anazitiseis": "Δημοφιλείς αναζητήσεις",
    "prosfora_imeras": "Προσφορά ημέρας",
    "snap_find_fotografise_tin": "Snap & Find: φωτογράφισε την παλιά σου συσκευή",
    "o_symvoylos_skeftetai": "Ο σύμβουλος σκέφτεται"
  },
  "energy": {
    "reyma_se_eyro": "Ρεύμα σε ευρώ",
    "ti_tha_plironeis_sti": "Τι θα πληρώνεις στη ΔΕΗ",
    "chronia_chrisis": "Χρόνια χρήσης"
  },
  "gallery": {
    "fotografia_proiontos": "φωτογραφία προϊόντος",
    "prosfora": "Προσφορά",
    "neo": "Νέο"
  },
  "cookies": {
    "politiki_cookies": "Πολιτική cookies",
    "metrisi_episkepsimotitas": "Μέτρηση επισκεψιμότητας",
    "aporripsi": "Απόρριψη",
    "apodochi_olon": "Αποδοχή όλων",
    "apothikeysi_epilogon": "Αποθήκευση επιλογών",
    "rythmiseis": "Ρυθμίσεις",
    "rythmiseis_cookies": "Ρυθμίσεις cookies"
  },
  "compareTray": {
    "sygkrine": "Σύγκρινε",
    "katharismos_sygkrisis": "Καθαρισμός σύγκρισης"
  },
  "wishlist": {
    "sygkrisi": "Σύγκριση"
  },
  "productRow": {
    "agora_me_1_klik": "Αγορά με 1 κλικ",
    "sto_kalathi": "Στο καλάθι"
  },
  "productGrid": {
    "den_vrethikan_proionta": "Δεν βρέθηκαν προϊόντα",
    "dokimase_na_afaireseis_kapoio": "Δοκίμασε να αφαιρέσεις κάποιο φίλτρο ή να αλλάξεις τον όρο αναζήτησης."
  },
  "pagination": {
    "proigoymeni": "‹ Προηγούμενη",
    "epomeni": "Επόμενη ›",
    "selides": "Σελίδες"
  },
  "wishlistGrid": {
    "i_lista_soy_einai": "Η λίστα σου είναι άδεια",
    "patise_tin_kardia_se": "Πάτησε την καρδιά σε ένα προϊόν για να το κρατήσεις εδώ.",
    "des_tis_prosfores": "Δες τις προσφορές"
  },
  "compareStacked": {
    "diaferei": "διαφέρει"
  },
  "specs": {
    "technikos_fakelos": "Τεχνικός φάκελος",
    "charaktiristika": "Χαρακτηριστικά",
    "energeiaki_etiketa": "Ενεργειακή ετικέτα"
  },
  "recentlyViewed": {
    "eides_prosfata": "Είδες πρόσφατα"
  },
  "stickyBar": {
    "charaktiristika": "Χαρακτηριστικά",
    "axiologiseis": "Αξιολογήσεις",
    "agora_me_1_klik": "Αγορά με 1 κλικ"
  },
  "mobileMenu": {
    "katigories": "Κατηγορίες",
    "menoy": "Μενού"
  },
  "breadcrumbs": {
    "diadromi": "Διαδρομή"
  },
  "energyChip": {
    "deltio_proiontos": "Δελτίο προϊόντος"
  },
  "stepper": {
    "vimata_agoras": "Βήματα αγοράς"
  },
  "consents": {
    "thema": "Θέμα",
    "apothikeytike": "Αποθηκεύτηκε"
  },
  "hero": {
    "kampanies": "Καμπάνιες",
    "epilogi_diafaneias": "Επιλογή διαφάνειας"
  },
  "bento": {
    "proteinomena": "Προτεινόμενα"
  },
  "ticker": {
    "emporika_minymata": "Εμπορικά μηνύματα"
  },
  "newsCard": {
    "diavase": "Διάβασε"
  },
  "greeting": {
    "kleisimo": "Κλείσιμο"
  },
  "carousel": {
    "proigoymeno": "Προηγούμενο",
    "epomeno": "Επόμενο"
  },
  "brandTiles": {
    "oi_selides_ton_kataskeyaston": "Οι σελίδες των κατασκευαστών",
    "des_ti_selida": "Δες τη σελίδα"
  }
} as const;
